### PR TITLE
Fail compilation on sign-comparison-warnings

### PR DESCRIPTION
**Pull request by beckerhe**
This PR straightens a difference in behaviour between GCC and Clang. GCC was failing on sign-comparison-warnings, but Clang was not. Now Clang also fails on these warnings.

### CODE REVIEW

**Comment by ronaldfw** [comment]
Should we fix those issues, though? These are potentially crashes and security issues. 

I'd even vote for having these warnings as errors in our CI.

**Comment by ronaldfw** [comment]
Ah, wait, this is for compiling conan packages, (right?), so we can't just fix those issues.

**Comment by beckerhe** [comment]
> Ah, wait, this is for compiling conan packages only (right?), so we can't just fix those issues.

No, we can fix it. If that's our policy I'm also fine with that. I'm not sure though if it brings a security benefit. I fixed several of these problems in the last month and none could have led to a problem.

But you just gave me an idea: Maybe we can enable the same warning/error in clang and get the check without adding another job to the CI. I will have a look...

**Comment by ronaldfw** [comment]
> But you just gave me an idea: Maybe we can enable the same warning/error in clang and get the check without adding another job to the CI. I will have a look...

That'd be great!

**Comment by beckerhe** [comment]
> > But you just gave me an idea: Maybe we can enable the same warning/error in clang and get the check without adding another job to the CI. I will have a look...
> 
> That'd be great!

It seems to work.
Ronald, thanks a lot for pushing back on this. Now we have a clearly better solution!

**Pull request merged**
