### PR TITLE
Throttle calls of UpdateAfterSymbolLoading

### PR DESCRIPTION
**Pull request by beckerhe**
This avoids that multiple subsequent calls to `UpdateAfterSymbolLoading`
block the UI and do the very same post processing over and over again.

The updates will be limited to at most once per second. If multiple
updates get requested during the same interval the will be combined and
only a single update will be executed after the second has passed.

This means when loading a capture post processing usually happens twice.
Once after the first module has been loaded, and once a second later when usually all other modules have finished loading.
Previously this happended once per module.

Test: Manual on Windows, with captures and live runs

### CODE REVIEW

**Review by karupayun — APPROVED** [review]
Nice solution Henning! I liked that the symbols was being updated more often, what do you think of setting to 500ms instead?

**Comment by beckerhe** [comment]
> Nice solution Henning! I liked that the symbols was being updated more often, what do you think of setting to 500ms instead?

I've considered that. But I didn't see much of a difference. The first post processing is launched when the `Capture Loading` dialog is still up. Once you get access to the main window you have to be very fast to click on Sampling or TopDown to even observe the second post processing. I think there are only 200ms between being able to click and when the second post processing happens. Furthermore 500ms might lead to more than 2 updates (which is not a big deal, but I still think that 1s is the better default for the user.) Have you tried this and think differently? Or is this more of a feeling?

**Comment by karupayun** [comment]
> > Nice solution Henning! I liked that the symbols was being updated more often, what do you think of setting to 500ms instead?
> 
> I've considered that. But I didn't see much of a difference. The first post processing is launched when the `Capture Loading` dialog is still up. Once you get access to the main window you have to be very fast to click on Sampling or TopDown to even observe the second post processing. I think there are only 200ms between being able to click and when the second post processing happens. Furthermore 500ms might lead to more than 2 updates (which is not a big deal, but I still think that 1s is the better default for the user.) Have you tried this and think differently? Or is this more of a feeling?

100% of a feeling. Feel free to ignore it.

But I might have understood you wrong. I expected that as we weren't updating that dataviews we weren't either updating the status in the symbols tab, but this is being updating as before? I was mostly worried about that UI-detail in the symbols tab that it's really nice.

**Comment by beckerhe** [comment]
> > > Nice solution Henning! I liked that the symbols was being updated more often, what do you think of setting to 500ms instead?
> > 
> > 
> > I've considered that. But I didn't see much of a difference. The first post processing is launched when the `Capture Loading` dialog is still up. Once you get access to the main window you have to be very fast to click on Sampling or TopDown to even observe the second post processing. I think there are only 200ms between being able to click and when the second post processing happens. Furthermore 500ms might lead to more than 2 updates (which is not a big deal, but I still think that 1s is the better default for the user.) Have you tried this and think differently? Or is this more of a feeling?
> 
> 100% of a feeling. Feel free to ignore it.
> 
> But I might have understood you wrong. I expected that as we weren't updating that dataviews we weren't either updating the status in the symbols tab, but this is being updating as before? I was mostly worried about that UI-detail in the symbols tab that it's really nice.

Oh. Good point. We might be able to do this update unthrottled. Let me check

**Comment by beckerhe** [comment]
> > > Nice solution Henning! I liked that the symbols was being updated more often, what do you think of setting to 500ms instead?
> > 
> > 
> > I've considered that. But I didn't see much of a difference. The first post processing is launched when the `Capture Loading` dialog is still up. Once you get access to the main window you have to be very fast to click on Sampling or TopDown to even observe the second post processing. I think there are only 200ms between being able to click and when the second post processing happens. Furthermore 500ms might lead to more than 2 updates (which is not a big deal, but I still think that 1s is the better default for the user.) Have you tried this and think differently? Or is this more of a feeling?
> 
> 100% of a feeling. Feel free to ignore it.
> 
> But I might have understood you wrong. I expected that as we weren't updating that dataviews we weren't either updating the status in the symbols tab, but this is being updating as before? I was mostly worried about that UI-detail in the symbols tab that it's really nice.

@karupayun I added a refresh for the module list independent of the throttle. PTAL!

**Review by karupayun — APPROVED** [review]
LGTM! Very very nice! :) :) :)

**Comment by beckerhe** [comment]
> LGTM! Very very nice! :) :) :)

Thanks Pablo! :)

**Pull request merged**
