### PR TITLE
Remove autosave flag

### PR DESCRIPTION
**Pull request by dimitry-**
Bug: http://b/187388305
Test: builds

### CODE REVIEW

**Review by florian-kuebler — APPROVED** [review]

**Comment by florian-kuebler** [comment]
LGTM

**Review by dpallotti — APPROVED** [review]
I'm fine with removing it but have you consider keeping it for internal use? Would we have downsides?

**Comment by dimitry-** [comment]
> I'm fine with removing it but have you consider keeping it for internal use? Would we have downsides?

I do not really see any use-case for disabling this flag... do you have something specific in mind?

**Comment by dpallotti** [comment]
> > I'm fine with removing it but have you consider keeping it for internal use? Would we have downsides?
> 
> I do not really see any use-case for disabling this flag... do you have something specific in mind?

I was just thinking that when developing and taking many captures it could be useful to just turn autosave off to prevent accumulating captures. But on the other hand maybe we shouldn't get used to a workflow that we don't support outside of development.

**Pull request merged**
