### PR TITLE
Merge release/1.55 into master

### PR DESCRIPTION
**Pull request by karupayun**

### CODE REVIEW

**Comment by beckerhe** [comment]
Hi Pablo,
there are two additional commits. That looks a bit fishy. Is that intended?

**Comment by karupayun** [comment]
Updated with a force push, because we've erased some PR from 1.55 release.

**Comment by karupayun** [comment]
> Hi Pablo,
> there are two additional commits. That looks a bit fishy. Is that intended?

In a GVC with Henning we agreed that is intended

**Comment by beckerhe** [comment]
> Hi Pablo,
> there are two additional commits. That looks a bit fishy. Is that intended?

For reference: There was a problem with pierric's commit. But having additional commits in here is normal and there was nothing wrong in that regard with the PR.

Looks good!

**Review by beckerhe — APPROVED** [review]
LGTM! Thanks Pablo!

**Review by IrinaShkviro — APPROVED** [review]

**Pull request merged**
