### PR TITLE
Clang-format everything after ColumnLimit change

### PR DESCRIPTION
**Pull request by dimitry-**
This applies new ColumnLimit to all *.h/*.cpp files.
    
    Test: builds

### CODE REVIEW

**Comment by dimitry-** [comment]
clang-format presumbit check does something strange:

clang-format determined the following necessary changes to your PR:
--- OrbitGl/TextBox.cpp	(before formatting)
+++ OrbitGl/TextBox.cpp	(after formatting)
@@ -90,9 +90,9 @@
     col = selectionColor;
   }
 
-  float z = a_IsHighlighted ? GlCanvas::Z_VALUE_CONTEXT_SWITCH
-            : isInactive    ? GlCanvas::Z_VALUE_BOX_INACTIVE
-                            : GlCanvas::Z_VALUE_BOX_ACTIVE;
+  float z = a_IsHighlighted
+                ? GlCanvas::Z_VALUE_CONTEXT_SWITCH
+                : isInactive ? GlCanvas::Z_VALUE_BOX_INACTIVE : GlCanvas::Z_VALUE_BOX_ACTIVE;
 
   Color color = col;
   if (a_IsPicking) {
--- OrbitGl/TopDownView.h	(before formatting)
+++ OrbitGl/TopDownView.h	(after formatting)
@@ -63,7 +63,7 @@
 class [[nodiscard]] TopDownFunction : public TopDownInternalNode {
  public:
   explicit TopDownFunction(uint64_t function_absolute_address, std::string function_name,
-                           TopDownNode* parent)
+                           TopDownNode * parent)
       : TopDownInternalNode{parent},
         function_absolute_address_{function_absolute_address},
         function_name_{std::move(function_name)} {}
@@ -101,7 +101,7 @@
 
 class [[nodiscard]] TopDownThread : public TopDownInternalNode {
  public:
-  explicit TopDownThread(int32_t thread_id, std::string thread_name, TopDownNode* parent)
+  explicit TopDownThread(int32_t thread_id, std::string thread_name, TopDownNode * parent)
       : TopDownInternalNode{parent}, thread_id_{thread_id}, thread_name_{std::move(thread_name)} {}
 
   [[nodiscard]] int32_t thread_id() const { return thread_id_; }


Here is the list of files that need formatting:
OrbitGl/TextBox.cpp
OrbitGl/TopDownView.h
--


I am going to ignore it for this commit.

**Comment by beckerhe** [comment]
> clang-format presumbit check does something strange:
> 
> ```
> clang-format determined the following necessary changes to your PR:
> --- OrbitGl/TextBox.cpp	(before formatting)
> +++ OrbitGl/TextBox.cpp	(after formatting)
> @@ -90,9 +90,9 @@
>      col = selectionColor;
>    }
>  
> -  float z = a_IsHighlighted ? GlCanvas::Z_VALUE_CONTEXT_SWITCH
> -            : isInactive    ? GlCanvas::Z_VALUE_BOX_INACTIVE
> -                            : GlCanvas::Z_VALUE_BOX_ACTIVE;
> +  float z = a_IsHighlighted
> +                ? GlCanvas::Z_VALUE_CONTEXT_SWITCH
> +                : isInactive ? GlCanvas::Z_VALUE_BOX_INACTIVE : GlCanvas::Z_VALUE_BOX_ACTIVE;
>  
>    Color color = col;
>    if (a_IsPicking) {
> --- OrbitGl/TopDownView.h	(before formatting)
> +++ OrbitGl/TopDownView.h	(after formatting)
> @@ -63,7 +63,7 @@
>  class [[nodiscard]] TopDownFunction : public TopDownInternalNode {
>   public:
>    explicit TopDownFunction(uint64_t function_absolute_address, std::string function_name,
> -                           TopDownNode* parent)
> +                           TopDownNode * parent)
>        : TopDownInternalNode{parent},
>          function_absolute_address_{function_absolute_address},
>          function_name_{std::move(function_name)} {}
> @@ -101,7 +101,7 @@
>  
>  class [[nodiscard]] TopDownThread : public TopDownInternalNode {
>   public:
> -  explicit TopDownThread(int32_t thread_id, std::string thread_name, TopDownNode* parent)
> +  explicit TopDownThread(int32_t thread_id, std::string thread_name, TopDownNode * parent)
>        : TopDownInternalNode{parent}, thread_id_{thread_id}, thread_name_{std::move(thread_name)} {}
>  
>    [[nodiscard]] int32_t thread_id() const { return thread_id_; }
> 
> 
> Here is the list of files that need formatting:
> OrbitGl/TextBox.cpp
> OrbitGl/TopDownView.h
> --
> ```
> 
> I am going to ignore it for this commit.

It's nothing strange. It's exactly the `.clang-format`-config-profile Florian and I talked about. If we want to have compatiblity between different versions of clang-format we need an explicit config file. If not the best solution is to use the same version of clang-format the CI uses which is clang-format-9.

Could you make a follow-up-PR with clang-format-9?

**Comment by dimitry-** [comment]
I am not sure, if you look at what CI clang-format wants to do to pointers I kind of like current version better. It seems like a bug in clang version on CI side.

**Comment by beckerhe** [comment]
> I am not sure, if you look at what CI clang-format wants to do to pointers I kind of like current version better. It seems like a bug in clang version on CI side.

I agree that the your version is for sure better looking. But I also don't care too much. To me a working clang-format-check on the CI is much more important. And since there is no way to bring the google-internal version of clang-format to the CI, I would rather use clang-format-9.

**Pull request merged**
