### PR TITLE
Rename OrbitClientModel to ClientModel and add namespace

### PR DESCRIPTION
**Pull request by dpallotti**

### CODE REVIEW

**Comment by dpallotti** [comment]
This ends up touching a lot of files, so let me know if it interferes with work you're doing (@dimitry- maybe?).

**Review by dimitry- — APPROVED** [review]

**Comment by dimitry-** [comment]
> This ends up touching a lot of files, so let me know if it interferes with work you're doing (@dimitry- maybe?).

No worries, I can rebase.

**Review by florian-kuebler — APPROVED** [review]
LGTM, thanks

**Review by beckerhe — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
