### PR TITLE
Fix crash when unhooking functions.

### PR DESCRIPTION
**Pull request by danielfenner**
Bug: http://b/207120901
Test: run locally

### CODE REVIEW

**Review by beckerhe — APPROVED** [review]

**Comment by danielfenner** [comment]
Hey, the four lines here have three authors according to "blame". Not sure who is comfortable reviewing this so I just added all of you ... ptal ...

**Comment by danielfenner** [comment]
Specifically: Is it okay to skip the rows with `function == nullptr` or is something else broken an function should never be null in the first place (in which case this "fix" would be horrible duct tape).

**Comment by beckerhe** [comment]
> Specifically: Is it okay to skip the rows with `function == nullptr` or is something else broken and function should never be null in the first place (in which case this "fix" would be horrible duct tape).

I have no idea. Does anybody else know?

**Review by dpallotti — APPROVED** [review]
> Specifically: Is it okay to skip the rows with function == nullptr or is something else broken and function should never be null in the first place (in which case this "fix" would be horrible duct tape).

I think it's correct now, I guess we don't have the `FunctionInfo*` if we haven't loaded symbols, but we have the menu actions if at least one frame is eligible.

This bug looks like it's been there for a while. It's worrying we never found it. So I'm wondering if something changed recently that made this code no longer work (but it doesn't look like it).

I was comparing with https://github.com/google/orbit/blob/main/src/DataViews/SamplingReportDataView.cpp: there we have a `SamplingReportDataView::GetFunctionsFromIndices` that indeed verifies that the `FunctionInfo*` is not nullptr. 

On note is that that method also prevents duplicates (e.g., in case of recursion), not sure if we want to do the same here.

**Comment by danielfenner** [comment]
> So I'm wondering if something changed recently that made this code no longer work (but it doesn't look like it, it's probably just that you have to select frames across two modules one of which is loaded and one of which isn't).

I'll quickly mention it in the standup; let's see, but I also think this just went unnotized.

> On note is that that method also prevents duplicates (e.g., in case of recursion), not sure if we want to do the same here (of course it's not directly related to the bug).

I think duplicates are not a problem here. With the disassembly and source code view we get multiple open windows and that is a bit weird but nothing too bad.

**Pull request merged**
