### PR TITLE
Fix ManualInstrumentationOnSilenus test

### PR DESCRIPTION
**Pull request by dpallotti**
This test is failing on the test machine on `CheckTimers`.
The cause seems to be that the "triangle.exe" track is too far down and hence
offscreen.
Use `FilterTracks` to make it visible (and do the same for the
"Render (async)" track).

Bug: http://b/239218513

Test: Ran locally with smaller window size.

### CODE REVIEW

**Review by danielfenner — APPROVED** [review]
lgtm, thanks!

**Review by florian-kuebler — APPROVED** [review]

**Review by karupayun — COMMENTED** [review]
I agree with this as a temporal solution but I would rather prefer to have a filter every time we check a Track (or for timers in this case). In that sense, we won't have this issue anymore.

Could I ask you to add a TODO?

**Review by karupayun — APPROVED** [review]
LGTM! Thanks for addressing my comment! :)

**Comment by dpallotti** [comment]
> I agree with this as a temporal solution but I would rather prefer to have a filter every time we check a Track (or for timers in this case). In that sense, we won't have this issue anymore.
> 
> Could I ask you to add a TODO?

This crossed my mind. I added a TODO. Note that this is a larger task:
- We need to make sure not to break existing tests;
- The track filter ORs the tokens split by spaces; this should be mostly fine but it's a bit different than matching by name exactly, which I believe is what `CheckTimers` does.

**Pull request merged**
