### PR TITLE
Enforce usage from the main thread on all of DataManager's methods

### PR DESCRIPTION
**Pull request by dpallotti**
Add `ORBIT_CHECK(std::this_thread::get_id() == main_thread_id_);` to all
methods. Re-add `DataManager` test to verify this.
Also, reorder method definitions to match declaration order.

Test: Play around with Orbit trying to make actions that are related to the
`DataManager`'s methods.

### CODE REVIEW

**Review by florian-kuebler — APPROVED** [review]
LGTM, thanks!

**Comment by beckerhe** [comment]
Sry, for being late. If you want I can look at it now. But since you just pushed I assume you wanna merge it soon (which is fine by me). Let me know if you prefer me to have a look.

**Comment by dpallotti** [comment]
> Sry, for being late. If you want I can look at it now. But since you just pushed I assume you wanna merge it soon (which is fine by me). Let me know if you prefer me to have a look.

Thanks, I think it's fine but up to you.

**Comment by beckerhe** [comment]
> > Sry, for being late. If you want I can look at it now. But since you just pushed I assume you wanna merge it soon (which is fine by me). Let me know if you prefer me to have a look.
> 
> Thanks, I think it's fine but up to you.

Great. In that case please just continue. :-)

**Pull request merged**
