### PR TITLE
Fix typo in register_tests

### PR DESCRIPTION
**Pull request by dimitry-**
Actually registers OrbitQtTests now.

### CODE REVIEW

**Comment by dimitry-** [comment]
hmm:

```
[ RUN      ] StatusListenerImpl.ShowAndClearOneMessage
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

**Comment by dimitry-** [comment]
I guess this is somewhat expected.. not sure what to do with it though. We can leave the test unregistered, I guess.

**Comment by beckerhe** [comment]
> I guess this is somewhat expected.. not sure what to do with it though. We can leave the test unregistered, I guess.

Can you try to add `export QT_QPA_PLATFORM=offscreen` to the bash-CI-build-script in `kokoro/builds/build.sh`?
Somewhere after the `We are inside the docker container`-comment should be fine.

**Comment by beckerhe** [comment]
> > I guess this is somewhat expected.. not sure what to do with it though. We can leave the test unregistered, I guess.
> 
> Can you try to add `export QT_QPA_PLATFORM=offscreen` to the bash-CI-build-script in `kokoro/builds/build.sh`?
> Somewhere after the `We are inside the docker container`-comment should be fine.

Okay, great. So it works at least on Linux. I'm not sure about Windows though. It might not work anymore when we move to docker. Could you wait a little bit longer before merging? I wanna try this out.

**Comment by beckerhe** [comment]
> > > I guess this is somewhat expected.. not sure what to do with it though. We can leave the test unregistered, I guess.
> > 
> > 
> > Can you try to add `export QT_QPA_PLATFORM=offscreen` to the bash-CI-build-script in `kokoro/builds/build.sh`?
> > Somewhere after the `We are inside the docker container`-comment should be fine.
> 
> Okay, great. So it works at least on Linux. I'm not sure about Windows though. It might not work anymore when we move to docker. Could you wait a little bit longer before merging? I wanna try this out.

Unfortunately I won't work when running inside a Windows docker container. We should probably disable the test registration in the windows on docker case.

Feel free to merge that here. I will take care of it in a subsequent PR.

**Pull request merged**
