### PR TITLE
Catch exception thrown by asio::write

### PR DESCRIPTION
**Pull request by dpallotti**
Bug: http://b/155464095

---
I'm open for suggestions on how to do this better/differently. At the same time, this is meant to be a limited-scope fix, as we are moving to gRPC and I'm not sure how much it's worth to investigate improving all these `Tcp...` classes.

### CODE REVIEW

**Comment by beckerhe** [comment]
Sorry for coming late to the party and now complaining.

I think it would be good to gracefully terminate the service at this point. Our workflow with SSH-deployment does not allow for reconnects anyway. If the connection is broken in some way, we need to stop.

My suggestion is to catch the exception somewhere higher up.  Probably in OrbitService::Run and gracefully terminate by setting exit_requested to true.

**Comment by dpallotti** [comment]
> Sorry for coming late to the party and now complaining.
> 
> I think it would be good to gracefully terminate the service at this point. Our workflow with SSH-deployment does not allow for reconnects anyway. If the connection is broken in some way, we need to stop.
> 
> My suggestion is to catch the exception somewhere higher up. Probably in OrbitService::Run and gracefully terminate by setting exit_requested to true.

@beckerhe I was expecting something like this, hence my premise. How would this look like, considering that `OrbitService::Run` is a different thread? It seems to me that this would require quite a rework of these `Tcp...` classes, while Dimitry is already working on gRPC.

**Comment by ronaldfw** [comment]
> My suggestion is to catch the exception somewhere higher up. Probably in OrbitService::Run and gracefully terminate by setting exit_requested to true.

I'd prefer if we catch exceptions for dependencies tightly around the callsites into those dependencies and then use our own error reporting / propagation mechanism (preferably error codes). 

But I agree with the overall goal of gracefully terminating here in case of an error and I don't know if it's easily possible to report the error upwards without just letting the exception bubble up.

**Comment by dpallotti** [comment]
> But I agree with the overall goal of gracefully terminating here in case of an error and I don't know if it's easily possible to report the error upwards without just letting the exception bubble up.

Again, maybe I'm missing something obvious, but this is not "up(wards)", this is between different threads. So I can try to make sense of this `TcpEntity` class and find a way to make `OrbitService` get the information that the connection is broken and it should terminate, if you think it's important, or we can rely on the ssh connection + watchdog and remove all this code once everything uses gRPC.

**Comment by ronaldfw** [comment]
> > But I agree with the overall goal of gracefully terminating here in case of an error and I don't know if it's easily possible to report the error upwards without just letting the exception bubble up.
> 
> Again, maybe I'm missing something obvious, but this is not "up(wards)", this is between different threads. So I can try to make sense of this `TcpEntity` class and find a way to make `OrbitService` get the information that the connection is broken and it should terminate, if you think it's important, or we can rely on the ssh connection + watchdog and remove all this code once everything uses gRPC.

I wasn't aware this was on a different thread.

**Comment by beckerhe** [comment]
> > > But I agree with the overall goal of gracefully terminating here in case of an error and I don't know if it's easily possible to report the error upwards without just letting the exception bubble up.
> > 
> > 
> > Again, maybe I'm missing something obvious, but this is not "up(wards)", this is between different threads. So I can try to make sense of this `TcpEntity` class and find a way to make `OrbitService` get the information that the connection is broken and it should terminate, if you think it's important, or we can rely on the ssh connection + watchdog and remove all this code once everything uses gRPC.
> 
> I wasn't aware this was on a different thread.

Yeah. Davide is right. I wasn't aware either. Sorry for the noise.

Sticking to the current solution is probably fine. There are other mechanism which should terminate the service like the stdin-EOF-detection or the watchdog.

**Pull request merged**
