### PR TITLE
Make DataView::GetToolTip return DataView::GetValue by default

### PR DESCRIPTION
**Pull request by dpallotti**
There are plenty of cases where the content of a cell of a `DataView` doesn't
fit in the width of the column. In some cases, even expanding the column is not
enough to reveal the full content, as the `DataView` itself is not wide enough.
We enable tooltips everywhere by making it show the content of the cell by
default.

Test: Take a capture, verify tooltips in all `DataView`s.

### CODE REVIEW

**Comment by dpallotti** [comment]
I'm assuming this is not controversial. Let's discuss if you think it is, in which case we need to enable tooltips for the columns in the `DataView`s that are most affected.

**Comment by vickyliu-go4it** [comment]
Happy to see this change. Code wise looks all good to me.

But I would like to discuss the special cases. The `PresetsDataView` shows the same tooltip for all columns. Sometimes the "Date Modified" column does not have enough space but the tooltip is still only related to the preset filepath and load state.
Shall we consider show GetValue as the tooltip for the "Data Modified" column instead?

**Comment by dpallotti** [comment]
> But I would like to discuss the special cases. The `PresetsDataView` shows the same tooltip for all columns. Sometimes the "Date Modified" column does not have enough space but the tooltip is still only related to the preset filepath and load state. Shall we consider show GetValue as the tooltip for the "Data Modified" column instead?

Hehe, you caught exactly the case that I was unsure how to handle and hence I didn't touch. The reason why I was unsure is that the "Modules" and Hooked Functions" columns make sense when seen together, because they have multiple rows with a 1-1 relation. However, the other columns can be tackled independently, and these two can be improved. I'll do that and come back to you.

**Comment by dpallotti** [comment]
@vickyliu-go4it So, I did a little rework of `PresetsDataView::GetToolTip`. The "Modules" and "Hooked Functions" columns show the same tooltip that merges the information of the two, I think it looks decent. The first column's tooltip shows "(loaded)" instead of "*" to indicate that the preset has been loaded. I left the "None of the modules in the preset can be loaded." string confined to the "Preset" column as it felt a bit too much to add it to the tooltip of every column now that they show different content.

Let me know what you think.

**Review by vickyliu-go4it — APPROVED** [review]
Just tried it and I really like the new tooltips! Thanks!

**Review by antonrohr — APPROVED** [review]

**Pull request merged**
