### PR TITLE
Remove DataManager::selected_callstack_events_by_thread_id_

### PR DESCRIPTION
**Pull request by dpallotti**
This was basically a duplication of
`CaptureData::selection_callstack_data_.callstack_events_by_tid_`.

Note that I also wanted to move `CaptureData::selection_callstack_data_` to the
`DataManager`, because the selection is not part of the capture.
The problem is that `CallstackData` is synchronized, so having it as a member of
`DataManager` clashes with the idea that everything in `DataManager` should be
accessed from the main thread, even if that member would indeed only have been
accessed from the main thread. This needs to be done in more steps, keeping only
`CallstackEvent`s (related to the selection) in `DataManager`.

Bug: http://b/214231145

Test: Capture Trata, make a few selections.

### CODE REVIEW

**Review by florian-kuebler — APPROVED** [review]
LGTM. Thanks.

Just to clarify,  we still agree on moving the selected callstacks completely out of capture data at some point, right?

**Comment by dpallotti** [comment]
> Just to clarify, we still agree on moving the selected callstacks completely out of capture data at some point, right?

Definitely. But it's not as simple as I thought as the synchronization requirements are different: the set of `CallstackEvent`s of the whole capture needs to be synchronized across the capture thread and the main thread, while the set of `CallstackEvent`s for the selection is only accessed by the main thread. So simply "splitting `CallstackData`" in two doesn't really work, because the part related to the `CallstackEvent` would need to be different based on whether it should be synchronized or not.

**Comment by florian-kuebler** [comment]
> > Just to clarify, we still agree on moving the selected callstacks completely out of capture data at some point, right?
> 
> Definitely. But it's not as simple as I thought as the synchronization requirements are different: the set of `CallstackEvent`s of the whole capture needs to be synchronized across the capture thread and the main thread, while the set of `CallstackEvent`s for the selection is only accessed by the main thread. So simply "splitting `CallstackData`" in two doesn't really work, because the part related to the `CallstackEvent` would need to be different based on whether it should be synchronized or not.

Makes sense. Thanks for the explanation.

**Review by karupayun — APPROVED** [review]
LGTM!

Can you link the previous PR where we created this duplication?

**Comment by dpallotti** [comment]
> Can you link the previous PR where we created this duplication?

It's more complicated than that. The duplication goes back a long long time and I'm not sure it can be attributed to one pull request. Originally the selected `CallstackEvent`s to show in the capture view were stored in the tracks and then in the `TimeGraph`. While the selection that is now in `CaptureData` came from a5d659ba93a950500ecc5156a81fb36a60e68006 but I think was already around in some form.

**Pull request merged**
