### PR TITLE
Limit the height of the input part of Mizar GUI

### PR DESCRIPTION
**Pull request by akopich**
This gives more space for the output part of the GUI.

Bug: http://b/239152833
Test: Manual

### CODE REVIEW

**Review by karupayun — COMMENTED** [review]
Hi Valeriy. Codewise LGTM, but I'd need a bit more context to understand what you are doing, either a screenshot to see if the 250 makes sense or either some explanation about what are input/output part of Mizar GUI are. 

The linked bug (http://b/239152833) doesn't have any dependence (parent/child) and also it doesn't have any explanation apart of that we want to limit the "input height".

**Comment by karupayun** [comment]
I've seen that you've just added an screenshot. I'll look at it.

**Review by karupayun — APPROVED** [review]
LGTM! :)

Nit: Next time I'd ask you to add the screenshot before asking for a review. :)

**Comment by akopich** [comment]
Thanks for the review. 

My action sequence was like
1. Send the PR
2. Assign Pablo
3. Oh! Pablo will ask for a screenshot!
4. Add the screenshot.

**Comment by karupayun** [comment]
> Thanks for the review.
> 
> My action sequence was like
> 
> 1. Send the PR
> 2. Assign Pablo
> 3. Oh! Pablo will ask for a screenshot!
> 4. Add the screenshot.

hahahahaha, 2 minutes later :P

**Pull request merged**
