### PR TITLE
QVector build issue (#4750)

### PR DESCRIPTION
**Pull request by GregorGall**
QVector has't got constructor from std::vector iterators, so
it's better to use static function: fromStdVector

### CODE REVIEW

**Comment by pierricgimmig** [comment]
Thanks for this @GregorGall!

**Review by pierricgimmig — APPROVED** [review]

**Comment by GregorGall** [comment]
> Thanks for this @GregorGall! Please sign CLA and we are good to merge.

I have already done it. That's kind of strange:

The following contributors were found for this pull request:

✅ 373b105 Author: @GregorGall <Gre******l50​@gmail.com>
✅ 05dfad4 Author: @pierricgimmig <pier*******mig​@gmail.com>
❌ 05dfad4 Co-Author: @orbitprofiler-bot <62639378+orbitprofiler-bot​@users.noreply.github.com>

(Only the first commit for a unique contributor is listed.)

**Review by florian-kuebler — APPROVED** [review]
Thanks.

I am very sorry for the inconveniences with the bot account. It is actually on an allow-list for the CLA, which for some reason is not working for co-authored commits. I am on this.

Until then, could you manually rebase/squash your change, and remove the bot as author?

**Comment by florian-kuebler** [comment]
So I fixed the issue with the bot. However, it will only apply for future commits from it. So you still need to rebase and remove the bot as co-author.

**Comment by florian-kuebler** [comment]
Thanks again for the fix. I resolved the issue with the bot and merged the change.

**Pull request merged**
