### PR TITLE
Add "Toggle capture" button and menu item, toggle capture with 'X' from everywhere

### PR DESCRIPTION
**Pull request by dpallotti**
#### Add and use QAction to toggle capture with 'X' from everywhere
Also add such action to the "File" menu.
Also add Ctrl+S and Ctrl+O shortcuts to save and open a capture.

Bug: http://b/156245865

---
A (somewhat) more sophisticated attempt than #543, that I closed.

### CODE REVIEW

**Comment by dpallotti** [comment]
Screenshot:
Screenshot from 2020-05-28 15-47-40

**Comment by ronaldfw** [comment]
Another comment: I would also not add a menu item, the button and shortcut are enough and you just clutter the menu with an item that doesn't really belong there.

**Comment by dpallotti** [comment]
> Thanks, I think it's important we add this, just two quick comments:
> 
> 1. I would like to change the wording on this to be "Start capture" and once you press this, switch to "Stop capture". Makes it much clearer which state you are in.
> 2. Buttons that extend over the entire length of a view like this are really ugly. I don't have a specific suggestion how to place this, but we should refine this.

1. I agree and I definitely thought about it, but in the end I went for this for simplicity. I'll look into it.
2. The point is that I don't really know where to place the button. If I leave it in the same place but have it as wide as the text (assuming I'm capable of that, not exactly a Qt expert here), then it might still be just as ugly with all that empty space on the two sides.

> Another comment: I would also not add a menu item, the button and shortcut are enough and you just clutter the menu with an item that doesn't really belong there.

I don't really agree that it doesn't belong, but either way, the reason for that was that it was the way way I found to have a QAction that can respond to 'X' from anywhere (apparently I can't attach it to the button itself). There's probably a better way but that was the first one I found.

**Comment by ronaldfw** [comment]
> I don't really agree that it doesn't belong, but either way, the reason for that was that it was the way way I found to have a QAction that can respond to 'X' from anywhere (apparently I can't attach it to the button itself). There's probably a better way but that was the first one I found.

I would not make UI choices based on "that's how I was able to implement it". Could you make this a hidden menu item as a workaround? (That way we don't have the menu item, but the implementation would still work.)

**Comment by dpallotti** [comment]
> > I don't really agree that it doesn't belong, but either way, the reason for that was that it was the way way I found to have a QAction that can respond to 'X' from anywhere (apparently I can't attach it to the button itself). There's probably a better way but that was the first one I found.
> 
> I would not make UI choices based on "that's how I was able to implement it". Could you make this a hidden menu item as a workaround? (That way we don't have the menu item, but the implementation would still work.)

Of course, but the two things seemed to go hand in hand with each other for me, as I said it seemed fitting to give the main action of the program a place in the menu. But if you don't want it to be there I'll find another way.

**Comment by pierricgimmig** [comment]
Hi Davide, I'm not sure about the 'X' from anywhere feature, don't we risk triggering unwanted captures when entering text thinking that a filter has focus for example?

Concerning the button, I was thinking about making a start/stop capture button in the OpenGl window, much like the "triangle button" to collapse tracks work.  I would have placed it in the top dark grey bar, probably in place of the "press H for help" text.  I was thinking of a red circle that would transform to a red square when pressed and vice versa.  This could be a good opportunity for you to get into the rendering code if you wanted btw, I could also make a prototype tomorrow.

**Comment by ronaldfw** [comment]
> Hi Davide, I'm not sure about the 'X' from anywhere feature, don't we risk triggering unwanted captures when entering text thinking that a filter has focus for example?

That's a good point. I think all we need is a button. This addresses discoverability on how to start/stop a capture, which is the primary concern.

**Comment by dpallotti** [comment]
> I'm not sure about the 'X' from anywhere feature, don't we risk triggering unwanted captures when entering text thinking that a filter has focus for example?

Well, I agree, this was because of http://b/156245865. In this pull request I had made it so that it would work when any tab is selected, but even restricting it to only when the "capture" tab is selected the problem would be the same. Also what if you're navigating the trace with the keyboard and instead of hitting for example 'S' you hit 'X' by mistake? Maybe we should change the shortcut to Ctrl-X or something like that? Or maybe the the button itself is enough?

**Comment by ronaldfw** [comment]
> Concerning the button, I was thinking about making a start/stop capture button in the OpenGl window, much like the "triangle button" to collapse tracks work. I would have placed it in the top dark grey bar, probably in place of the "press H for help" text. I was thinking of a red circle that would transform to a red square when pressed and vice versa. This could be a good opportunity for you to get into the rendering code if you wanted btw, I could also make a prototype tomorrow.

I think there should be text like "Start capture" and "Stop capture" to make it very clear. A red circle may mean "press here to start recording" or "we are already recording". Other tools use a "Play" button (triangle pointing to the right), though I also don't really like it.

**Comment by ronaldfw** [comment]
> Or maybe the button itself is enough?

My vote is for just a button.

**Comment by pierricgimmig** [comment]
> I think there should be text like "Start capture" and "Stop capture" to make it very clear.

Fair enough, in this case, I think using ImGui would be the easiest way to go if we want to place the button in the top bar of the capture window, using less vertical space.  Let me create a prototype real quick... won't be long.

**Comment by ronaldfw** [comment]
> Well, I agree, this was because of http://b/156245865. 

Apologies for not being explicit about how to actually resolve the issue raised in that bug (that users have to click into the capture field before they can press 'x' to capture). 

In general, we should explicitly discuss all user visible changes in more detail and how to resolve them between at least @pierricgimmig and myself. IMO, the "discussion" can also be a PR and prototype, sometimes that's easier than other methods, but the downside is that some work will likely get thrown out.

**Pull request closed without merging**
