### PR TITLE
Remove sampling_report from OrbitApp

### PR DESCRIPTION
**Pull request by vwbaker**
SamplingReport is meant to be a controller/ui helper for the Sampling tab and this should not be updated or created in Orbit App.  Instead, only pass the data it needs and that it will not change.

### CODE REVIEW

**Review by florian-kuebler — APPROVED** [review]
LGTM. Will the TopDown/BottomUp views follow?

**Comment by vwbaker** [comment]
> LGTM. Will the TopDown/BottomUp views follow?

Not exactly.  My main idea is to make some sort of Selection object that contains all the information to quickly switch between full_capture/selection/inspection views.  This means keeping the top_down/bottom_up views as part of that object since creating them is time consuming and makes sense not to recreate them.  The report doesn't take much time and it is much closer to a controller than a immutable data structure like the top_down/bottom_up views.  If it turns out that FillReport is a bottleneck, we can extract that part into it's own data class but SamplingReport itself does a lot more controller/ui work.

**Comment by florian-kuebler** [comment]
> > LGTM. Will the TopDown/BottomUp views follow?
> 
> Not exactly. My main idea is to make some sort of Selection object that contains all the information to quickly switch between full_capture/selection/inspection views. This means keeping the top_down/bottom_up views as part of that object since creating them is time consuming and makes sense not to recreate them. The report doesn't take much time and it is much closer to a controller than a immutable data structure like the top_down/bottom_up views. If it turns out that FillReport is a bottleneck, we can extract that part into it's own data class but SamplingReport itself does a lot more controller/ui work.

Sounds good. Thanks for the explanation.

**Review by beckerhe — APPROVED** [review]
Cool. Otherwise LGTM. Thank you! :-)

**Pull request merged**
