### PR TITLE
Adjust frame track colors to be similar when durations are similar

### PR DESCRIPTION
**Pull request by ronaldfw**
When all frame times are fairly similar, we want all colors to be fairly
similar, as there is no need to point out small differences by using
a different color. We solve this by adjusting the maximum upwards a bit
when computing colors (and only then!) and when the minimum and
maximum are close to each other. Colors are still interpolated between
the real minimum and the adjusted maximum, so there will be still some
variation in color.

When the maximum is "large enough" compared with the minimum, 
the behavior is not changed.

Tested: Manually tested frame track.
Bug: http://b/174224286

### CODE REVIEW

**Comment by ronaldfw** [comment]
Screenshot before the change:
frame_track_original

Screenshot after the change:
frame_track_new

**Review by karupayun — APPROVED** [review]
LGTM Ronald!!! Clearly an improvement!

I posted 2 images here.

The first one is VkQueuePresent not being that constantly as your screenshot. You could seem there some blue columns, which I think that they are ok.
first VkQueuePresent

But this second one has one VkQueue frame timer with duration 12.29s which makes all the rest being too blueish. 
second example

This makes me think that we should still use the average instead of the minumum. And instead of making a difference with the bigger/smaller than the average, choose average + 10% instead. So, the difference started to be really noticed when you are 10% bigger than the average. 

What do you think?

**Comment by ronaldfw** [comment]
> What do you think?

You are right, as long as we are using minimum and only the minimum, single outliers can completely mess up this scheme. I like your suggestion to base this on the average.

**Comment by ronaldfw** [comment]
For your capture:

Old code (before this PR):

example_karupayun_before

New code (current version, based on your suggestion):

example_karupayun_new

**Comment by karupayun** [comment]
I like it! :)

LGTM again!

**Comment by ronaldfw** [comment]
Thanks for the review @karupayun

**Pull request merged**
