### PR TITLE
Remove MoveFilesToDocuments module

### PR DESCRIPTION
**Pull request by dpallotti**
This was added in 1.66 when we moved the default location for captures and presets from `%appdata%` to `Documents`. I don't think there's any point keeping this operation around now.

Test: Build.

### CODE REVIEW

**Comment by dpallotti** [comment]
Any thought on this?

**Review by florian-kuebler — APPROVED** [review]
I would be very much in favour of removing this.

**Review by beckerhe — APPROVED** [review]
No objections! LGTM!

**Review by antonrohr — APPROVED** [review]
I like this!

**Pull request merged**
