### PR TITLE
Fix crashpad recipe

### PR DESCRIPTION
**Pull request by IrinaShkviro**
- Added openssl_lib_order.patch that fixes openssl libs order
- Update windows_adaptions.patch to be in line with new commit id

### CODE REVIEW

**Comment by beckerhe** [comment]
Hey, this looks good. Two small things:
- Can you update the version number?
- And can you remove `contrib/conan/recipes/depot_tools_installer/conanfile.py` from the commit history? You add the file in the first commit and delete it in the second commit which means it's still part of the history. You could either merge this two commits which would be fine for me or you could split the second commit such that the deletion is in a separate commit and then apply this commit as a fixup to the first commit.

**Comment by beckerhe** [comment]
> Hey, this looks good. Two small things:
> 
> * Can you update the version number?
> * And can you remove `contrib/conan/recipes/depot_tools_installer/conanfile.py` from the commit history? You add the file in the first commit and delete it in the second commit which means it's still part of the history. You could either merge this two commits which would be fine for me or you could split the second commit such that the deletion is in a separate commit and then apply this commit as a fixup to the first commit.

As discussed OOB the version number was already updated and is not an issue here.

**Comment by IrinaShkviro** [comment]
Thank you for the review!

**Comment by beckerhe** [comment]
I will let you know when the new packages are built and uploaded. Currently I'm doing grpc and protobuf, so the machines are still blocked a little bit.

**Pull request merged**
