### PR TITLE
Redraw capture window when TimeGraph::Zoom is called

### PR DESCRIPTION
**Pull request by ronaldfw**
The capture window was not redrawn when using the jump to first/min/max/last actions as TimeGraph::NeedsUpdate() would not actually cause a redraw of the capture window. 

This PR makes all changes so that "update needed" => "redraw needed" is now an invariant of the TimeGraph class. In particular, NeedsUpdate() now also sets m_NeedsRedraw to true. 

Clarifying comments are added.

### CODE REVIEW

**Comment by ronaldfw** [comment]
> Looks reasonable to me. But I also don't know much about TimeGraph. So if that's not urgent I'd recommend to wait for Pierric to have a look.

The first version called a method in CaptureWindow to redraw, which I was worried about a bit. I'm now using the NeedsRedraw() method on TimeGraph (which I just didn't see earlier) and I'm reasonably confident that that's ok. 

I believe that in other cases where this method was used (e.g. to zoom into a textbox when double-clicking on a textbox), the redraw was simply triggered because the mouse pointer was in the capture window in all cases. Redraw is for example needed for the green vertical line. Explicitly calling NeedsRedraw() should actually be correct in all these cases, but was simply not necessary due to a side effect elsewhere. 

This is not urgent though, so I'll wait for @pierricgimmig to take a look.

**Comment by karupayun** [comment]
Only a comment: In my new pull request (which I'm not going to submit at least until Monday), I made a modification and now the capture window is redraw after jumping.

**Comment by ronaldfw** [comment]
> Only a comment: In my new pull request (which I won't merge in master at least until Monday), I made a similar modification and now the capture window is redraw after jumping.

Thanks for pointing that out!

I had a look and I think the reason it works in your change is that you call UpdatePrimitives(), which also sets m_NeedsRedraw. The whole UpdatePrimitives() call is not needed though.

**Comment by karupayun** [comment]
Perfect! :)

**Comment by pierricgimmig** [comment]
Hi @ronaldfw, the reason behind NeedsRedraw() and NeedsUpdate() is that we want to minimize the rendering work.  Essentially, if nothing changes, then we don't need to draw.  In the case where we do want to redraw, but that we don't need to update the timer data to be rendered, then we call NeedsRedraw().  On zoom, we are changing the coordinates of the vertices to be drawn, so we need to "UpdatePrimitives".  I'd suggest using NeedsUpdate() instead of NeedsRedraw(). The fact that NeedsRedraw() alone fixes the problem is a bit surprising to me actually.  I'll dig a bit deeper and get back to you.

**Comment by pierricgimmig** [comment]
@ronaldfw , I dug deeper, and there was indeed a bug. Please see https://github.com/google/orbit/pull/796. TL;DR: We should use NeedsUpdate() here.

**Comment by ronaldfw** [comment]
Hmm, I agree that NeedsUpdate() is needed as we zoom, but only calling NeedsUpdate() does not actually cause a redraw. I don't yet see how the changes in #796 actually fix the issue.

**Comment by ronaldfw** [comment]
Looking at the code, it looks to me like TimeGraph::IsRedrawNeeded should return m_NeedsRedraw || m_NeedsUpdate? It seems to me that m_NeedsUpdate should always imply m_NeedsRedraw (or in other words, m_NeedsUpdate => m_NeedsRedraw should be an invariant of the class). However when you call NeedsUpdate(), you can end up in a situation where m_NeedsUpdate is true but m_NeedsRedraw is false.

**Comment by ronaldfw** [comment]
Ok, I understand now how #796 now requires us to use NeedsUpdate() here.

**Comment by ronaldfw** [comment]
PTAL, thanks!

**Comment by pierricgimmig** [comment]
Yeah I just went through that logic again, it's a bit messy, it is definitely the case that we can request an update that won't happen until the next redraw, which is weird.

**Comment by ronaldfw** [comment]
So, should I merge this in the current state?

**Comment by ronaldfw** [comment]
Thanks so much for the thorough review and discussion, @pierricgimmig!

**Pull request merged**
