### PR TITLE
Remove unused files from repo root

### PR DESCRIPTION
**Pull request by beckerhe**
This removes the Windows batch script which have been deprecated and
converted to powershell a long time ago.

Furthermore this remove the windows cmake readme which is outdated.

I believe `pack.bat` is also not in use anymore.

### CODE REVIEW

**Review by dpallotti — APPROVED** [review]
Thanks!

By the way, what about `release_notes.txt`?

**Review by pierricgimmig — APPROVED** [review]
Yes, thanks Henning, I've been wanting to do the same!

**Comment by beckerhe** [comment]
> Thanks!
> 
> By the way, what about `release_notes.txt`?

Yes, good Point. @pierricgimmig Do you have any strong feelings about the release_notes.txt file?
Since it's not up-to-date it might be confusing to new potential contributors.

**Comment by pierricgimmig** [comment]
> Yes, good Point. @pierricgimmig Do you have any strong feelings about the release_notes.txt file?

@beckerhe , this flew under my radar, but let's remove it yes!

**Pull request merged**
