### PR TITLE
Improving includes

### PR DESCRIPTION
**Pull request by antonrohr**
Test: Compiles & Unit tests

This was done by following clang-tidy recommendations and partially by search & replace (stddef.h -> cstddef)

### CODE REVIEW

**Comment by beckerhe** [comment]
> Test: Compiles & Unit tests
> 
> This was done by following clang-tidy recommendations and partially by search & replace (stddef.h -> cstddef)

If you replace stddef.h by cstddef, then you should also replace size_t by std::size_t. cstddef does not guarantee availability of size_t in the global namespace. Same for ptrdiff_t.

And the same of stdint.h/cstdint and all the uint*_t types.

**Comment by beckerhe** [comment]
> > Test: Compiles & Unit tests
> > This was done by following clang-tidy recommendations and partially by search & replace (stddef.h -> cstddef)
> 
> If you replace stddef.h by cstddef, then you should also replace size_t by std::size_t. cstddef does not guarantee availability of size_t in the global namespace. Same for ptrdiff_t.
> 
> And the same of stdint.h/cstdint and all the uint*_t types.

And yes, right now this is not real problem but it will become one with C++ modules.

**Comment by dpallotti** [comment]
> If you replace stddef.h by cstddef, then you should also replace size_t by std::size_t.

Can't we just stick to `stddef.h`? `size_t` is *exteremely* more common than `std::size_t` in all C++ code I've ever seen.

**Comment by antonrohr** [comment]
> Can't we just stick to stddef.h? size_t is exteremely more common than std::size_t in all C++ code I've ever seen.

Yeah, maybe that is the better idea. I like it even less with `uint64_t` to `std::uint64_t`

**Comment by antonrohr** [comment]
Second attempt of this PR. 

I am now not touching the standard library headers, but just remove headers that are not directly used in the file (based on clang-tidy). The added includes to some files are the ones that used to be included by transitivity.

**Review by dpallotti — APPROVED** [review]

**Pull request merged**
