### PR TITLE
Refactor, created namespace OrbitGgp

### PR DESCRIPTION
**Pull request by antonrohr**
Trying to make more but smaller CLs :)

### CODE REVIEW

**Comment by beckerhe** [comment]
It's nice to have that namespace. I'm currently thinking about if we should remove the "Ggp"-prefix in all the class names. But I'm undecided. What is your take on this?

**Comment by antonrohr** [comment]
I had the thought as well. I did not include it, because it seemed a lot of work and this was only supposed to be a prerequisite PR to introduce an Error class based on std::error_code. Which itself was only supposed to be a prerequisite PR for fixing a bug. 

But thinking about it again, it would make things a lot cleaner. 
Going to do it as part of this PR, brb

**Comment by beckerhe** [comment]
> I had the thought as well. I did not include it, because it seemed a lot of work and this was only supposed to be a prerequisite PR to introduce an Error class based on std::error_code. Which itself was only supposed to be a prerequisite PR for fixing a bug.
> 
> But thinking about it again, it would make things a lot cleaner.
> Going to do it as part of this PR, brb

Ah I see your train of thought. It's just that as soon as we talk about namespace the naming-discussion is close by. :innocent:

**Comment by antonrohr** [comment]
I added another commit with the renaming. ptal

**Pull request merged**
