### PR TITLE
Make TimerChain const

### PR DESCRIPTION
**Pull request by dimitry-**
By design it is append-only data structure and
it now it does not allow modifications of TimerInfos
added.

Bug: http://b/194090304
Test: builds

### CODE REVIEW

**Review by pierricgimmig — APPROVED** [review]
LGTM, thanks for this Dimitry. I was expecting to see some code where an element of a chain was modified after insertion, was that removed in a previous PR?

**Comment by dimitry-** [comment]
> LGTM, thanks for this Dimitry. I was expecting to see some code where an element of a chain was modified after insertion, was that removed in a previous PR?

Yes it was removed together with the textbox

**Review by karupayun — APPROVED** [review]
I haven't removed in my pr the non-const operator []. Should we also remove them in this PR?

`[[nodiscard]] orbit_client_protos::TimerInfo& operator[](std::size_t idx) { return data_[idx]; }`

**Comment by dimitry-** [comment]
> I haven't removed in my pr the non-const operator []. Should we also remove them in this PR?
> 
> `[[nodiscard]] orbit_client_protos::TimerInfo& operator[](std::size_t idx) { return data_[idx]; }`

yes - removed it as well.

**Pull request merged**
