### PR TITLE
Enforce consistent formatting across different versions of clang-format

### PR DESCRIPTION
**Pull request by florian-kuebler**
Each version of clang-format has its own definition of Google style.
Recent fails in the presubmit check showed that there are differences
in the latest version and the one from the CI (which is clang-format-9).

This PR dumps the Google style definition from clang-format-9 into
the .clang-format file instead of relying on what the version below
has defined as such.

### CODE REVIEW

**Comment by florian-kuebler** [comment]
Seem that the presubmit check we have currently is failing for #1026.

**Comment by florian-kuebler** [comment]
As discussed offline, the root cause is not ignoring the file but differences in the Google style in different versions.

**Comment by beckerhe** [comment]
> As discussed offline, the root cause is not ignoring the file but differences in the Google style in different versions.

When I take this file and try to format some code with clang-format-7 I get the following error:
```
YAML:11:18: error: invalid boolean
AlignOperands:   Align
                 ^~~~~
```

It seems the config was generated with a more modern version of clang-format. We shouldn't impose that requirement on our potential external contributors. The Google-style between LLVM-7 and LLVM-9 didn't change. It's just the naming in the configuration file. So there are no disadvantages for us using a config generated by LLVM-7. (Sorry for the confusion, I think we discussed that in chat but I failed to make myself clear.)

We should also loop in @pierricgimmig  and @dimitry-. If I remember correctly they both had objections regarding an explicit configuration.

**Comment by florian-kuebler** [comment]
I'd suggest to go then with a config file generated with clang-format-7.

**Comment by florian-kuebler** [comment]
> I think we should go with the short-version and have final arbitrator on the presubmit check side. (we also want it to be the lasters stable version of clang-format)

This is somewhat inconvenient and arbitrary. Locally, you then need to know which version is used at the check side. E.g. you can't rely on your IDE or even pre-commit hooks.

**Comment by dimitry-** [comment]
> > I think we should go with the short-version and have final arbitrator on the presubmit check side. (we also want it to be the lasters stable version of clang-format)
> 
> This is somewhat inconvenient and arbitrary. Locally, you then need to know which version is used at the check side. E.g. you can't rely on your IDE or even pre-commit hooks.

Don't tools use whichever clang-format you have installed on your machine? If this is the case the idea would be to always use the version used by CI.

**Comment by florian-kuebler** [comment]
> > > I think we should go with the short-version and have final arbitrator on the presubmit check side. (we also want it to be the lasters stable version of clang-format)
> > 
> > 
> > This is somewhat inconvenient and arbitrary. Locally, you then need to know which version is used at the check side. E.g. you can't rely on your IDE or even pre-commit hooks.
> 
> Don't tools use whichever clang-format you have installed on your machine? If this is the case the idea would be to always use the version used by CI.

Exactly, tools like IDEs usually use whats on your system. So if you have a newer version then on the kokoro machine (which is true for our workstations), you result in different formattings. The idea of this change would be, that you can use what ever version you want and will result in what is on the kokoro machine.

**Comment by dimitry-** [comment]
> > > > I think we should go with the short-version and have final arbitrator on the presubmit check side. (we also want it to be the lasters stable version of clang-format)
> > > 
> > > 
> > > This is somewhat inconvenient and arbitrary. Locally, you then need to know which version is used at the check side. E.g. you can't rely on your IDE or even pre-commit hooks.
> > 
> > 
> > Don't tools use whichever clang-format you have installed on your machine? If this is the case the idea would be to always use the version used by CI.
> 
> Exactly, tools like IDEs usually use whats on your system. So if you have a newer version then on the kokoro machine (which is true for our workstations), you result in different formattings. The idea of this change would be, that you can use what ever version you want and will result in what is on the kokoro machine.

But this is not the case right? there are bugs which are fixed in later version which could result in different formatting even if you expand everything. I do not think this is a solution. It seems to me it introduces more problems then it solves. It is hard to read, hard to maintain, if are still capped by whichever version is used to generate this file.

**Comment by beckerhe** [comment]
> > > > > I think we should go with the short-version and have final arbitrator on the presubmit check side. (we also want it to be the lasters stable version of clang-format)
> > > > 
> > > > 
> > > > This is somewhat inconvenient and arbitrary. Locally, you then need to know which version is used at the check side. E.g. you can't rely on your IDE or even pre-commit hooks.
> > > 
> > > 
> > > Don't tools use whichever clang-format you have installed on your machine? If this is the case the idea would be to always use the version used by CI.
> > 
> > 
> > Exactly, tools like IDEs usually use whats on your system. So if you have a newer version then on the kokoro machine (which is true for our workstations), you result in different formattings. The idea of this change would be, that you can use what ever version you want and will result in what is on the kokoro machine.
> 
> But this is not the case right? there are bugs which are fixed in later version which could result in different formatting even if you expand everything. I do not think this is a solution. It seems to me it introduces more problems then it solves. It is hard to read, hard to maintain, if are still capped by whichever version is used to generate this file.

As far as I know bugs in clang-format are always fixed by introducing an additional option which is not enabled by default. So having a verbose config will fix that because bugfixes won't be enabled by default.

**Comment by florian-kuebler** [comment]
> > > > > > I think we should go with the short-version and have final arbitrator on the presubmit check side. (we also want it to be the lasters stable version of clang-format)
> > > > > 
> > > > > 
> > > > > This is somewhat inconvenient and arbitrary. Locally, you then need to know which version is used at the check side. E.g. you can't rely on your IDE or even pre-commit hooks.
> > > > 
> > > > 
> > > > Don't tools use whichever clang-format you have installed on your machine? If this is the case the idea would be to always use the version used by CI.
> > > 
> > > 
> > > Exactly, tools like IDEs usually use whats on your system. So if you have a newer version then on the kokoro machine (which is true for our workstations), you result in different formattings. The idea of this change would be, that you can use what ever version you want and will result in what is on the kokoro machine.
> > 
> > 
> > But this is not the case right? there are bugs which are fixed in later version which could result in different formatting even if you expand everything. I do not think this is a solution. It seems to me it introduces more problems then it solves. It is hard to read, hard to maintain, if are still capped by whichever version is used to generate this file.
> 
> As far as I know bugs in clang-format are always fixed by introducing an additional option which is not enabled by default. So having a verbose config will fix that because bugfixes won't be enabled by default.

And we already had it twice, that system was different to kokoro.

**Comment by dimitry-** [comment]
I am still convinced we shouldn't fix the version of Google style. We probably want to move forward with it.

**Comment by florian-kuebler** [comment]
As discussed offline, source of truth is the latest version on the CI and we will add this version to the documentation.

**Pull request closed without merging**
