### PR TITLE
Cache addresses for which not an epilog was successfully detected

### PR DESCRIPTION
**Pull request by dpallotti**
While we cannot cache the addresses for which we detected an epilog, as we
actually have to simulate the effects of the rest of that epilog, we can cache
the addresses for which we detected that we are _not_ in an epilog. These are
the majority anyway, as most samples are not going to be in an epilog.

In my usual experiments, this is a 15 to 20% performance improvement on the
average time to unwind one frame, for example because it saves us from a lot of
disassemblying.

Bug: http://b/237625163

Test:
- Add unit test.
- Capture a complex game running on Wine and verify no worsening of unwind error
  rate.
- Verify performance gain with ad-hoc instrumentation.

### CODE REVIEW

**Comment by dpallotti** [comment]
@florian-kuebler FYI

**Review by ronaldfw — APPROVED** [review]
LGTM

**Comment by ronaldfw** [comment]
I assume the cache can become quite large for somewhat longer captures (?). I would think that it's still better to get rid of capstone entirely with a custom detection approach, but as a stop-gap solution, this should be fine.

**Comment by dpallotti** [comment]
> I assume the cache can become quite large for somewhat longer captures (?). I would think that it's still better to get rid of capstone entirely with a custom detection approach, but as a stop-gap solution, this should be fine.

The fact that we only store at most one address per sample makes it such that the size of the cache should stay manageable for a reasonable capture length. As you say, if we get rid of capstone the cache could become useless or counterproductive (but maybe not), so at that point we need to re-evaluate. I added a comment stating that.

**Comment by florian-kuebler** [comment]
> > The fact that we only store at most one address per sample makes it such that the size of the cache should stay manageable for a reasonable capture length.
> 
> Ah, good way of looking at it. Yes, makes sense that the size will be okay.

I think the size could become a problem, if we decide to not only cache if an address is not in an epilogue, but also how to handle the epilogue in case the address is in the epilogue (like cache a "summary" function).

But that would be an option for an optimization after removing the capstone dependency.

**Pull request merged**
