### PR TITLE
Add .git-blame-ignore-revs file

### PR DESCRIPTION
**Pull request by dimitry-**
This file contains list of commits doing
bulk changes to repository. Commits listed
in this file are ignored by git blame.

Run following command to enable it:
git config blame.ignoreRevsFile .git-blame-ignore-revs

### CODE REVIEW

**Comment by pierricgimmig** [comment]
Awesome, thanks!

**Comment by pierricgimmig** [comment]
Suggestion: can we add comments with the reason why commits were added to the list?

**Comment by florian-kuebler** [comment]
Thanks. This will make git blame much better for us!

**Comment by dimitry-** [comment]
> Suggestion: can we add comments with the reason why commits were added to the list?

done,

**Pull request merged**
