### PR TITLE
Package LinuxTracingIntegrationTests in Orbit.zip

### PR DESCRIPTION
**Pull request by dpallotti**
So that it can be used in YHITI.

Bug: http://b/160756664

Test: Manually triggered
http://sponge2.corp.google.com/fa3b700a-d67d-4efb-a85d-4cc873eb2346 and
http://sponge2.corp.google.com/38d9aa07-d985-4253-bad3-eff9bde40e55.

### CODE REVIEW

**Review by beckerhe — COMMENTED** [review]
Looks good, can you trigger a nightly job from your branch to see if it works?

You have to go the fusion page http://fusion/, then search for the build `orbitprofiler/builds/linux/ggp_relwithdebinfo/nightly`, then trigger a build for this job. In the dialog, you can specify your fork and your branch name as a source.

**Comment by dpallotti** [comment]
> Looks good, can you trigger a nightly job from your branch to see if it works?
> 
> You have to go the fusion page http://fusion/, then search for the build `orbitprofiler/builds/linux/ggp_relwithdebinfo/nightly`, then trigger a build for this job. In the dialog, you can specify your fork and your branch name as a source.

Thanks for the pointer. Indeed that failed. My guess is that I have to change `conanfile.py` as well, so I'm trying again with that change. Correct me if I'm wrong.

**Comment by dpallotti** [comment]
> > Looks good, can you trigger a nightly job from your branch to see if it works?
> > You have to go the fusion page http://fusion/, then search for the build `orbitprofiler/builds/linux/ggp_relwithdebinfo/nightly`, then trigger a build for this job. In the dialog, you can specify your fork and your branch name as a source.
> 
> Thanks for the pointer. Indeed that failed. My guess is that I have to change `conanfile.py` as well, so I'm trying again with that change. Correct me if I'm wrong.

This seems to work now: http://sponge2.corp.google.com/fa3b700a-d67d-4efb-a85d-4cc873eb2346.

The concern I have is that `LinuxTracingIntegrationTests` is 167 MB. So should I strip it?

**Comment by beckerhe** [comment]
> > Looks good, can you trigger a nightly job from your branch to see if it works?
> > You have to go the fusion page http://fusion/, then search for the build `orbitprofiler/builds/linux/ggp_relwithdebinfo/nightly`, then trigger a build for this job. In the dialog, you can specify your fork and your branch name as a source.
> 
> Thanks for the pointer. Indeed that failed. My guess is that I have to change `conanfile.py` as well, so I'm trying again with that change. Correct me if I'm wrong.

Yes, that makes sense!

**Review by danielfenner — APPROVED** [review]
Just in case you haven't found it already yourself - this is how the stripping for the test should work: 

https://github.com/google/orbit/blob/ae9ffa822aedd332b94668011c27d1e7bc9e39ec/src/Service/CMakeLists.txt#L68

Otherwise lgtm.

**Comment by dpallotti** [comment]
> Just in case you haven't found it already yourself - this is how the stripping for the test should work:
> 
> https://github.com/google/orbit/blob/ae9ffa822aedd332b94668011c27d1e7bc9e39ec/src/Service/CMakeLists.txt#L68

Yep, thanks. I'm stripping both `LinuxTracingIntegrationsTests` and `libLinuxTracingIntegrationTestPuppetSharedObject.so` now.

**Comment by beckerhe** [comment]
> > Just in case you haven't found it already yourself - this is how the stripping for the test should work:
> > https://github.com/google/orbit/blob/ae9ffa822aedd332b94668011c27d1e7bc9e39ec/src/Service/CMakeLists.txt#L68
> 
> Yep, thanks. I'm stripping both `LinuxTracingIntegrationsTests` and `libLinuxTracingIntegrationTestPuppetSharedObject.so` now.

You should also add "self.copy"-lines for the resulting ".debug" files to the conanfile.py. This will store the .debug files in our bucket, but not put them into the ZIP file.

**Comment by dpallotti** [comment]
> You should also add "self.copy"-lines for the resulting ".debug" files to the conanfile.py. This will store the .debug files in our bucket, but not put them into the ZIP file.

Thanks! Done.

**Review by beckerhe — APPROVED** [review]
LGTM!

**Comment by dpallotti** [comment]
I've triggered one last job from fusion to double check.

**Comment by dpallotti** [comment]
> I've triggered one last job from fusion to double check.

http://sponge2.corp.google.com/38d9aa07-d985-4253-bad3-eff9bde40e55

**Comment by dpallotti** [comment]
`unit-test-coverage` keeps failing but I can't see any details. Could this be because `LinuxTracingIntegrationsTests` is now stripped and is registered as test (although it doesn't really do anything as it's not run as root)?

**Comment by beckerhe** [comment]
Good question. Here is the log: https://fusion2.corp.google.com/invocations/c3617a91-7b40-44c5-8814-f379d569647c/targets/orbitprofiler%2Fbuilds%2Flinux%2Fcoverage_clang9%2Fpresubmit/log

Adding @antonrohr. He might know what's going on

**Comment by dpallotti** [comment]
> Good question. Here is the log: https://fusion2.corp.google.com/invocations/c3617a91-7b40-44c5-8814-f379d569647c/targets/orbitprofiler%2Fbuilds%2Flinux%2Fcoverage_clang9%2Fpresubmit/log
> 
> Adding @antonrohr. He might know what's going on

#2058 does the same but removes the `register_test(LinuxTracingIntegrationTests)` and it fails the same way: http://sponge2/ee2932e8-d78d-473b-9267-e3f73248af0c

**Comment by beckerhe** [comment]
> > Good question. Here is the log: https://fusion2.corp.google.com/invocations/c3617a91-7b40-44c5-8814-f379d569647c/targets/orbitprofiler%2Fbuilds%2Flinux%2Fcoverage_clang9%2Fpresubmit/log
> > Adding @antonrohr. He might know what's going on
> 
> #2058 does the same but removes the `register_test(LinuxTracingIntegrationTests)` and it fails the same way: http://sponge2/ee2932e8-d78d-473b-9267-e3f73248af0c

I assume it's because of the separate .debug file, but I don't know why. @antonrohr should know.

**Comment by dpallotti** [comment]
> I assume it's because of the separate .debug file, but I don't know why. @antonrohr should know.

Seems like it, #2060 does the same as this change but without stripping and unit-test-coverage succeeds: http://sponge2/63403a10-c1df-4287-bde9-a23ee3a888dd

**Comment by antonrohr** [comment]
The problem is the coverage report cannot be generated by the `contrib/unit_test_coverage/generate_coverage_report.sh` script. This is the case because the script reads the contents of the `lib` folder and uses it as an input for `llvm-cov` to generate the report. The lib folder now contains `libLinuxTracingIntegrationTestPuppetSharedObject.so.debug` which makes the call to `llvm-cov` fail. 

This can be fixed by filtering for `.debug` files in `generate_coverage_report.sh` by changing line 21 to 
```
LIB_FILE_FILTER="\.debug\|VkLayer_Orbit_implicit.json"
```

Screenshot 2021-03-12 at 09 29 18

**Review by antonrohr — APPROVED** [review]

**Comment by dpallotti** [comment]
> This can be fixed by filtering for `.debug` files in `generate_coverage_report.sh` by changing line 21 to
> 
> ```
> LIB_FILE_FILTER="\.debug\|VkLayer_Orbit_implicit.json"
> ```

That makes sense, thanks!

**Pull request merged**
