### PR TITLE
Remove enable_stale_features flag and "Callstack" tab

### PR DESCRIPTION
**Pull request by dpallotti**
The "Callstack" tab is obsolete and unmaintaned, let's remove it.
This also clarifies the usage of `DataViewType::kCallstack` (callstack in the
"Sampling" tab).
Let's also remove the flag, that is now unnecessary and was once guarding more
UI parts.

### CODE REVIEW

**Review by antonrohr — APPROVED** [review]
More cleanup is always a welcome change! Thank you

**Review by beckerhe — APPROVED** [review]
Cool!

**Comment by antonrohr** [comment]
I renamed DataManagerUpdateModuleInfosFuzzer.cpp to ModuleListFuzzer.cpp. Sorry for the rebase inconvenience.

**Comment by dpallotti** [comment]
> I renamed DataManagerUpdateModuleInfosFuzzer.cpp to ModuleListFuzzer.cpp. Sorry for the rebase inconvenience.

No worries, it's just GitHub complaining!

**Pull request merged**
