### PR TITLE
Don't fail in front of UNWIND_INFOs with version 2

### PR DESCRIPTION
**Pull request by dpallotti**
Version 2 adds the undocumented `UWOP_EPILOG`. Don't use it and keep relying on
epilog detection in all cases, but handle it gracefully.

More information and links in the bug.

Bug: http://b/233328376

Test: 
- Extend unit tests.
- Tried on Silenus game that showed this. Unwinding now proceeds correctly
from the one address that was affected by this.

### CODE REVIEW

**Review by ronaldfw — APPROVED** [review]
LGTM!

**Comment by ronaldfw** [comment]
> Sorry, missed this: unit tests should be adapted to include skipping the op code and making sure we proceed only for correct versions.

You should actually see unit tests failing, e.g. PeCoffUnwindInfoEvaluatorTest::eval_fails_with_unsupported_unwind_instruction.

**Comment by dpallotti** [comment]
> Sorry, missed this: unit tests should be adapted to include skipping the op code and making sure we proceed only for correct versions.

I modified/added some unit tests. Let me know if you think they are enough or not.

**Review by ronaldfw — APPROVED** [review]
Looks great, thanks!

LGTM

**Pull request merged**
