### PR TITLE
limit GetAllTracks to ThreadTrack

### PR DESCRIPTION
**Pull request by dimitry-**
It is only used in ThreadTrack there is no need
for it to be virtual.

Test: builds

### CODE REVIEW

**Review by karupayun — COMMENTED** [review]
Codewise, LGTM!

But I don't understand why you said that you are limiting GetAllTracks to ThreadTrack and in the code you are limiting to TimerTrack (who includes AsyncTrack and FrameTrack for example)

**Comment by vickyliu-go4it** [comment]
LGTM!

Can we move this `GetAllChains` method from `TimerTrack` to `ThreadTrack`?

**Review by vickyliu-go4it — APPROVED** [review]

**Comment by dimitry-** [comment]
> LGTM!
> 
> Can we move this `GetAllChains` method from `TimerTrack` to `ThreadTrack`?

The plan is to remove it as well in next PR.

**Comment by dimitry-** [comment]
> Codewise, LGTM!
> 
> But I don't understand why you said that you are limiting GetAllTracks to ThreadTrack and in the code you are limiting to TimerTrack (who includes AsyncTrack and FrameTrack for example)

fixing the commit message.

**Review by pierricgimmig — APPROVED** [review]

**Pull request merged**
