### PR TITLE
Make jump actions inactive during the capture

### PR DESCRIPTION
**Pull request by akopich**
This should be disabled, as this might lead to crashes.

Tests: Manual
Bug: http://b/229958104

### CODE REVIEW

**Review by vickyliu-go4it — COMMENTED** [review]
Thanks for finding this!

Maybe the `LiveFunctionsDataViewTest::ContextMenuEntriesArePresentCorrectly` should also be updated to check this case.

**Review by karupayun — APPROVED** [review]
LGTM! :)

**Comment by akopich** [comment]
@vickyliu-go4it 
> Maybe the `LiveFunctionsDataViewTest::ContextMenuEntriesArePresentCorrectly` should also be updated to check this case.

Thanks for the great point. I've extended the test.

**Review by vickyliu-go4it — APPROVED** [review]
LGTM! Thanks for updating the test also!

**Pull request merged**
