### PR TITLE
Add enable symbol store checkboxes to ui

### PR DESCRIPTION
**Pull request by vickyliu-go4it**
With this change, we added the checkboxes to enable searching for symbols in Stadia and Microsoft symbol stores in Symbol Locations Dialog.

Bug: http://b/239166878

http://screenshot/9DZ5ag8JRCc6dYA
(The redundant "will be used" has been removed, but I'm to lazy to take a new screenshot 🙈  )

### CODE REVIEW

**Review by florian-kuebler — APPROVED** [review]
LGTM. Nice!

**Comment by vickyliu-go4it** [comment]
Update layout of the symbol location dialog http://screenshot/47hqGywWMyCeny6.

**Review by antonrohr — COMMENTED** [review]
Code-wise this looks great. I do have some ideas on how to improve the text / wording. Lets do that offline

**Comment by vickyliu-go4it** [comment]
A new look http://screenshot/QXd2r2EDV9LFVQC

**Comment by vickyliu-go4it** [comment]
A even newer look http://screenshot/9FG5vdU5ap55yvh

**Comment by vickyliu-go4it** [comment]
Got the LGTM from Anton offline so I'm going to submit it ;-)

**Pull request merged**
