### PR TITLE
Enable building OrbitVulkanLayer on Linux (not just Stadia)

### PR DESCRIPTION
**Pull request by dimitry-**

### CODE REVIEW

**Comment by dimitry-** [comment]
@dpallotti there is a failing test now - can you please take a look (once it fails in CI), it might be related to your change from yesterday.

**Review by beckerhe — COMMENTED** [review]
There was a reason why we didn't enable that for all Linux builds. But that might be obsolete by now. I don't remember. Florian, do you?

Otherwise this looks good to me.

**Comment by dpallotti** [comment]
> @dpallotti there is a failing test now - can you please take a look (once it fails in CI), it might be related to your change from yesterday.

Which one?

**Comment by dimitry-** [comment]
> > @dpallotti there is a failing test now - can you please take a look (once it fails in CI), it might be related to your change from yesterday.
> 
> Which one?

VulkanLayerControllerTest.WillCreateDispatchTableAndVulkanLayerProducerAndAdvanceLinkageOnCreateInstance

**Comment by dpallotti** [comment]
> > > @dpallotti there is a failing test now - can you please take a look (once it fails in CI), it might be related to your change from yesterday.
> > 
> > 
> > Which one?
> 
> VulkanLayerControllerTest.WillCreateDispatchTableAndVulkanLayerProducerAndAdvanceLinkageOnCreateInstance

Which of my change might it be related to? This seems to be for @florian-kuebler .

**Comment by dimitry-** [comment]
Apparently it breaks CI:

````
[ 71%] Building CXX object src/OrbitVulkanLayer/CMakeFiles/OrbitVulkanLayer.dir/DispatchTable.cpp.o
In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
/mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:240:44: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
      CHECK(device_dispatch_table_.at(key).ResetQueryPoolEXT != nullptr);
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:77:20: note: expanded from macro 'CHECK'
    if (UNLIKELY(!(assertion))) {       \
                   ^~~~~~~~~
/mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:62:44: note: expanded from macro 'UNLIKELY'
#define UNLIKELY(cond) __builtin_expect(!!(cond), 0)
                                           ^~~~
In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
/mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:241:45: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
      return device_dispatch_table_.at(key).ResetQueryPoolEXT;
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:74:18: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
  dispatch_table.ResetQueryPoolEXT = absl::bit_cast<PFN_vkResetQueryPoolEXT>(
  ~~~~~~~~~~~~~~ ^
3 errors generated.
````

@beckerhe looks like VkLayerDispatchTable does not have members we want. are we using old version of vulkan there?

**Comment by beckerhe** [comment]
> Apparently it breaks CI:
> 
> ```
> [ 71%] Building CXX object src/OrbitVulkanLayer/CMakeFiles/OrbitVulkanLayer.dir/DispatchTable.cpp.o
> In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
> /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:240:44: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
>       CHECK(device_dispatch_table_.at(key).ResetQueryPoolEXT != nullptr);
>             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
> /mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:77:20: note: expanded from macro 'CHECK'
>     if (UNLIKELY(!(assertion))) {       \
>                    ^~~~~~~~~
> /mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:62:44: note: expanded from macro 'UNLIKELY'
> #define UNLIKELY(cond) __builtin_expect(!!(cond), 0)
>                                            ^~~~
> In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
> /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:241:45: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
>       return device_dispatch_table_.at(key).ResetQueryPoolEXT;
>              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
> /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:74:18: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
>   dispatch_table.ResetQueryPoolEXT = absl::bit_cast<PFN_vkResetQueryPoolEXT>(
>   ~~~~~~~~~~~~~~ ^
> 3 errors generated.
> ```
> 
> @beckerhe looks like VkLayerDispatchTable does not have members we want. are we using old version of vulkan there?

We use whatever the debian container provides.

**Comment by florian-kuebler** [comment]
> > Apparently it breaks CI:
> > ```
> > [ 71%] Building CXX object src/OrbitVulkanLayer/CMakeFiles/OrbitVulkanLayer.dir/DispatchTable.cpp.o
> > In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
> > /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:240:44: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
> >       CHECK(device_dispatch_table_.at(key).ResetQueryPoolEXT != nullptr);
> >             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
> > /mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:77:20: note: expanded from macro 'CHECK'
> >     if (UNLIKELY(!(assertion))) {       \
> >                    ^~~~~~~~~
> > /mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:62:44: note: expanded from macro 'UNLIKELY'
> > #define UNLIKELY(cond) __builtin_expect(!!(cond), 0)
> >                                            ^~~~
> > In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
> > /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:241:45: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
> >       return device_dispatch_table_.at(key).ResetQueryPoolEXT;
> >              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
> > /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:74:18: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
> >   dispatch_table.ResetQueryPoolEXT = absl::bit_cast<PFN_vkResetQueryPoolEXT>(
> >   ~~~~~~~~~~~~~~ ^
> > 3 errors generated.
> > ```
> > 
> > 
> > @beckerhe looks like VkLayerDispatchTable does not have members we want. are we using old version of vulkan there?
> 
> We use whatever the debian container provides.

Ah now I remember again. We are using the vkResetQueryPoolEXT, which was not available everywhere. However, if I am not wrong the version on the workstations is actually recent enough to support this. @beckerhe do you know if we can upgrade the version on the CI?

**Comment by beckerhe** [comment]
> > > Apparently it breaks CI:
> > > ```
> > > [ 71%] Building CXX object src/OrbitVulkanLayer/CMakeFiles/OrbitVulkanLayer.dir/DispatchTable.cpp.o
> > > In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
> > > /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:240:44: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
> > >       CHECK(device_dispatch_table_.at(key).ResetQueryPoolEXT != nullptr);
> > >             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
> > > /mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:77:20: note: expanded from macro 'CHECK'
> > >     if (UNLIKELY(!(assertion))) {       \
> > >                    ^~~~~~~~~
> > > /mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:62:44: note: expanded from macro 'UNLIKELY'
> > > #define UNLIKELY(cond) __builtin_expect(!!(cond), 0)
> > >                                            ^~~~
> > > In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
> > > /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:241:45: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
> > >       return device_dispatch_table_.at(key).ResetQueryPoolEXT;
> > >              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
> > > /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:74:18: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
> > >   dispatch_table.ResetQueryPoolEXT = absl::bit_cast<PFN_vkResetQueryPoolEXT>(
> > >   ~~~~~~~~~~~~~~ ^
> > > 3 errors generated.
> > > ```
> > > 
> > > 
> > > @beckerhe looks like VkLayerDispatchTable does not have members we want. are we using old version of vulkan there?
> > 
> > 
> > We use whatever the debian container provides.
> 
> Ah now I remember again. We are using the vkResetQueryPoolEXT, which was not available everywhere. However, if I am not wrong the version on the workstations is actually recent enough to support this. @beckerhe do you know if we can upgrade the version on the CI?

Yes. But it's quite some work.

The better way is to finally switch to the vulkan-headers conan package.

**Comment by florian-kuebler** [comment]
> > > > Apparently it breaks CI:
> > > > ```
> > > > [ 71%] Building CXX object src/OrbitVulkanLayer/CMakeFiles/OrbitVulkanLayer.dir/DispatchTable.cpp.o
> > > > In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
> > > > /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:240:44: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
> > > >       CHECK(device_dispatch_table_.at(key).ResetQueryPoolEXT != nullptr);
> > > >             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
> > > > /mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:77:20: note: expanded from macro 'CHECK'
> > > >     if (UNLIKELY(!(assertion))) {       \
> > > >                    ^~~~~~~~~
> > > > /mnt/github/orbitprofiler/src/OrbitBase/include/OrbitBase/Logging.h:62:44: note: expanded from macro 'UNLIKELY'
> > > > #define UNLIKELY(cond) __builtin_expect(!!(cond), 0)
> > > >                                            ^~~~
> > > > In file included from /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:5:
> > > > /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.h:241:45: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
> > > >       return device_dispatch_table_.at(key).ResetQueryPoolEXT;
> > > >              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
> > > > /mnt/github/orbitprofiler/src/OrbitVulkanLayer/DispatchTable.cpp:74:18: error: no member named 'ResetQueryPoolEXT' in 'VkLayerDispatchTable_'
> > > >   dispatch_table.ResetQueryPoolEXT = absl::bit_cast<PFN_vkResetQueryPoolEXT>(
> > > >   ~~~~~~~~~~~~~~ ^
> > > > 3 errors generated.
> > > > ```
> > > > 
> > > > 
> > > > @beckerhe looks like VkLayerDispatchTable does not have members we want. are we using old version of vulkan there?
> > > 
> > > 
> > > We use whatever the debian container provides.
> > 
> > 
> > Ah now I remember again. We are using the vkResetQueryPoolEXT, which was not available everywhere. However, if I am not wrong the version on the workstations is actually recent enough to support this. @beckerhe do you know if we can upgrade the version on the CI?
> 
> Yes. But it's quite some work.
> 
> The better way is to finally switch to the vulkan-headers conan package.

Okay, we should probably tackle this in the fixit-week then.

**Comment by florian-kuebler** [comment]
With #2059 this was done. So I am closing this PR.

**Pull request closed without merging**
