### PR TITLE
Add OrbitClientGgp to collector

### PR DESCRIPTION
**Pull request by kisenshi**
Add _OrbitClientGgp_ binary to the collector zip for integration in the installer.

### CODE REVIEW

**Review by beckerhe — COMMENTED** [review]
Hi Cris,
as I've said before. This looks good to me.

But I forgot about one thing that we need to discuss. This is adding OrbitClientGgp to our production debian packages which means users will pay for this with an increased size of the debian package. Maybe that's negligible - I have no feeling for that. Could you maybe check the size of the debian package and also the size of the two included binaries for comparison?

**Comment by kisenshi** [comment]
I just check the size of the packages with and without the client and I get 3.5M and 6.6M. 

I include below the output of the sizes of the files in `orbit/build_debian_test`:

Before the change:
```
~/Projects/orbit/build_debian_test/package$ ls -lah
total 6.8M
drwxr-xr-x  3 crisguerrero primarygroup 4.0K Sep 22 16:20 .
drwxr-x--- 22 crisguerrero primarygroup  12K Sep 22 16:20 ..
drwxr-xr-x  2 crisguerrero primarygroup 4.0K Sep 22 16:20 bin
-rw-r-----  1 crisguerrero primarygroup 8.7K Sep 22 16:20 conaninfo.txt
-rw-r--r--  1 crisguerrero primarygroup  433 Sep 22 16:20 conanmanifest.txt
-rw-r-----  1 crisguerrero primarygroup 1.3K Sep 22 09:29 LICENSE
-rw-r--r--  1 crisguerrero primarygroup 114K Sep 22 16:16 NOTICE
-rw-r--r--  1 crisguerrero primarygroup 6.6M Sep 22 16:20 OrbitProfiler-xxxxxxxx.deb
```

After the change:
```
~/Projects/orbit/build_debian_test/package$ ls -lah
total 3.6M
drwxr-xr-x  3 crisguerrero primarygroup 4.0K Sep 22 16:46 .
drwxr-x--- 22 crisguerrero primarygroup  12K Sep 22 16:46 ..
drwxr-xr-x  2 crisguerrero primarygroup 4.0K Sep 22 16:46 bin
-rw-r-----  1 crisguerrero primarygroup 8.7K Sep 22 16:46 conaninfo.txt
-rw-r--r--  1 crisguerrero primarygroup  321 Sep 22 16:46 conanmanifest.txt
-rw-r-----  1 crisguerrero primarygroup 1.3K Sep 22 09:29 LICENSE
-rw-r-----  1 crisguerrero primarygroup 114K Sep 22 16:44 NOTICE
-rw-r--r--  1 crisguerrero primarygroup 3.5M Sep 22 16:46 OrbitProfiler-xxxxxxx.deb
```

**Comment by beckerhe** [comment]
> I just checked the size of the packages with and without the client and I get 3.5M and 6.6M.
> 
> I include below the command and input where I got this information from:
> 
> Before the change:
> 
> ```
> ~/Projects/orbit/build_debian_test/package$ ls -lah
> total 6.8M
> 4.0K Sep 22 16:20 .
> 12K Sep 22 16:20 ..
> 4.0K Sep 22 16:20 bin
> 8.7K Sep 22 16:20 conaninfo.txt
> 433 Sep 22 16:20 conanmanifest.txt
> 1.3K Sep 22 09:29 LICENSE
> 114K Sep 22 16:16 NOTICE
> 6.6M Sep 22 16:20 OrbitProfiler-xxxxxxxx.deb
> ```
> 
> After the change:
> 
> ```
> ~/Projects/orbit/build_debian_test/package$ ls -lah
> total 3.6M
>  4.0K Sep 22 16:46 .
>  12K Sep 22 16:46 ..
>  4.0K Sep 22 16:46 bin
>  8.7K Sep 22 16:46 conaninfo.txt
>  321 Sep 22 16:46 conanmanifest.txt
>  1.3K Sep 22 09:29 LICENSE
>  114K Sep 22 16:44 NOTICE
>  3.5M Sep 22 16:46 OrbitProfiler-xxxxxxx.deb
> ```

Okay, that's what I suspected. It's basically doubling the size. I see two ways: We could either take some measurements to be sure that this is not affecting the user experience. Or we create two independent debian packages for the two tools.

@ronaldfw / @danielfenner WDYT?

**Comment by danielfenner** [comment]
> @ronaldfw / @danielfenner WDYT?

Hmm, I see the point of uploading additional 3mb that we don't really need during normal operation. Additionally I will probably add another command line program to test / list the contents of the capture (as we discussed briefly in the Monday meeting).

Maybe it is smarter to just put the binaries in the Collector.zip such that they end up in the collector folder in the final installation  and have the e2e tests deploy them "manually" as needed. Neither Cristina's client nor the test / list utility will need to have the setuid bit set; that would be the only thing that only works via the .deb.

**Comment by danielfenner** [comment]
Just chatted with Henning - we agree that the client should end up "next to the .deb". You can have a look here: https://github.com/google/orbit/blob/40371da31fc4a131c1c52fca20ce9659004d1add/kokoro/builds/build.sh#L188

Just cp the executable into Orbit/collector/ and it will end up in Collector.zip (which is then used to assemble the binary distribution).

**Comment by ronaldfw** [comment]
We definitely want to keep installation / startup time for Orbit as fast as possible, so I'm definitely in favor of not including the client in the .deb package. Suggestion from @danielfenner sounds great!

**Comment by beckerhe** [comment]
@kisenshi Feel free to ping me if something is unclear!

**Comment by kisenshi** [comment]
Great, I will take a look; thanks a lot!

**Comment by kisenshi** [comment]
I reverted the change that included the ggp agent in the debian package and updated the build to include it in the collector instead. Thanks!

**Review by beckerhe — APPROVED** [review]
LGTM. Thanks Chris.

Just one thing: Can you entirely remove the old commit and the reverted one?

**Review by danielfenner — APPROVED** [review]
Code lgtm! Please adjust commit message / PR description when merging.

**Comment by kisenshi** [comment]
I have removed the old commits and updated the PR title and description. Waiting for checks to finish to merge. Thanks a lot!

**Pull request merged**
