### PR TITLE
Enforce defaulted-function-deleted warning

### PR DESCRIPTION
**Pull request by dimitry-**
Test: builds

### CODE REVIEW

**Review by antonrohr — APPROVED** [review]
lgtm, but I did not compile it. I was counting on the CI checks, but they did not run for some reason

**Comment by dimitry-** [comment]
CI did not trigger for this change for some reason, can you please take a look?

**Review by beckerhe — APPROVED** [review]
Great. I thought about adding this in a different context as well. Thanks!

**Comment by beckerhe** [comment]
@dimitry- Could you amend the commit and push again? That should (hopefully) trigger the CI.

**Pull request merged**
