### PR TITLE
Fixed copyright year in project files

### PR DESCRIPTION
**Pull request by sidhys1**
Some of the project files have a 2021 copyright year, while the others have a 2020 copyright year. I've went through each file, and updated the files with an old copyright year.

I hope this helped :)

Also this might be one of the biggest pull requests, I'm not sure. (626 changed files)

### CODE REVIEW

**Comment by sidhys1** [comment]
@googlebot I fixed it.

**Comment by sidhys1** [comment]
Is this bot broken 😕

**Comment by dimitry-** [comment]
we don't change year in headers for existing files.

**Comment by ronaldfw** [comment]
@sidhys1 Thanks for the PR. As @dimitry- pointed out, we don't change the year in existing files. Make sure to open an issue first if you want to contribute to indicate what you want to do. Then we have a chance to point you in the right direction or clarify if it's not something we want.

**Pull request closed without merging**
