### PR TITLE
Hide text on subtracks if parent is collapsed

### PR DESCRIPTION
**Pull request by vwbaker**
Bug: http://b/189194884

### CODE REVIEW

**Comment by vwbaker** [comment]
I overrode the IsCollapsed() function in the submission subtrack where the parent is also a track. I'm worried this may have other repercussions, but as I played around with the UI, it doesn't look like it changed anything else.

If we have other subtracks, it may need to be modified there as well just to be consistent...

Another note: when we collapse threads, the bars get smaller as well. As it is, the graphics bars don't; do we want to add this functionality as well?

Thanks!
Tori

**Review by florian-kuebler — APPROVED** [review]
>I overrode the IsCollapsed() function in the submission subtrack where the parent is also a track.

I think this is the way to go. We want the subtrack to behave as collapsed when the parent is collapsed, so why not just collapse it. Thanks!
Other consequences could in theory be the E2E tests, as they were also using the `IsCollapsed` function, but as above, if the parent is collapsed, we also want the child be collapsed. If you want to be sure, you could however run the E2E tests locally (instructions can be found here: go/stadia-orbit-integration-test, but you would need to get your system in the right state first).

>And if we have other subtracks that evaluate IsCollapsed, it may need to be modified there as well just to be consistent...

The `MajorPageFaultsTrack` is also a subtrack of the `PageFaultsTrack`. That actually looks like it is doing exactly the same.

>Another note: when we collapse threads, the bars get smaller in height as well. As it is, the graphics bars don't; do we want to add this functionality as well?

That's a great idea. Feel free to create a bug for this or do it right away (in a different PR). IIRC, the smaller height view was added after the tracks were created.

**Review by karupayun — APPROVED** [review]
Nice PR Tori! I like it! In the future we might be interested in create the notion of "subtrack" and we can include this as it works recursively :)

**Comment by vwbaker** [comment]
Thanks both! Created http://b/194804216 for height issue.

**Pull request merged**
