### PR TITLE
Demangle function names when processing FullAddressInfo

### PR DESCRIPTION
**Pull request by dimitry-**
Test: run ServiceTests
Bug: http://b/180397173

### CODE REVIEW

**Review by florian-kuebler — APPROVED** [review]
LGTM, thanks!

**Review by dpallotti — APPROVED** [review]
Where were they demangled before your big refactoring of protos?

**Comment by dimitry-** [comment]
> Where were they demangled before your big refactoring of protos?

yes - it LinuxTracingHandler (previous implementation)

I wonder if I should change the function_name in FullAddressInfo to mangled_function_name for clarity... this is kind of implicit now. We have mangled string in FullAdressInfo and demangled in AddressInfo

**Comment by dpallotti** [comment]
> We have mangled string in FullAdressInfo and demangled in AddressInfo

Ok, this is a bit weird honestly. What about demangling somewhere else then, like right after unwinding where `FullAddressInfo` is produced or even on the client side? Where are names from the symbols demangled?

**Comment by dimitry-** [comment]
> > We have mangled string in FullAdressInfo and demangled in AddressInfo
> 
> Ok, this is a bit weird honestly. What about demangling somewhere else then, like right after unwinding where `FullAddressInfo` is produced or even on the client side? Where are names from the symbols demangled?

makes sense. At least we are consistent in this case.

**Comment by dpallotti** [comment]
> > > We have mangled string in FullAdressInfo and demangled in AddressInfo
> > 
> > 
> > Ok, this is a bit weird honestly. What about demangling somewhere else then, like right after unwinding where `FullAddressInfo` is produced or even on the client side? Where are names from the symbols demangled?
> 
> makes sense. At least we are consistent in this case.

Not sure which one of the two you are referring to, but if I get it correctly names from loaded modules are unmangled as soon as possible in `ElfFile`, so I would just do something similar and unwind before producing `FullAddressInfo`. Or otherwise we could unmangle everything on the client side, but then it should be everything.

**Review by dpallotti — APPROVED** [review]

**Review by florian-kuebler — APPROVED** [review]
Still LGTM. Thanks!

**Pull request merged**
