### PR TITLE
Merge 1.58 back into main

### PR DESCRIPTION
**Pull request by beckerhe**
Hello reviewers,
as you know, the merge back is readjusting the history but makes no changes to the main branch.

Can you please check whether you release branch hotfix has been merged back into main? While preparing
this PR is got some merge conflicts which could mean a hotfix wasn't ported over to the main branch.

### CODE REVIEW

**Review by reichlfl — APPROVED** [review]
Mine is in main already. I'm wondering what happened here since the "Files changed" view is completely empty?

**Comment by beckerhe** [comment]
> Mine is in main already. I'm wondering what happened here since the "Files changed" view is completely empty?

Yes, that's correct. The purpose of this commit is not to make any changes to the main branch, but rather to "fix" the history.

**Comment by florian-kuebler** [comment]
LGTM, thanks!

**Comment by beckerhe** [comment]
For the record: I checked if Ronald's fix is in main. And yes it is indeed. PR #1675 

Merging now...

Thank you all

**Pull request merged**
