### PR TITLE
Fix Source Paths Mapping problem

### PR DESCRIPTION
**Pull request by beckerhe**
This fixes the problem that we had seen in the demo. With this change, source paths mappings in Unreal work well.

### CODE REVIEW

**Comment by beckerhe** [comment]
@antonrohr No hurries. This has a low priority regarding the release going on in parallel.

**Comment by antonrohr** [comment]
I havent gotten to this yet. I did not forget this. I will do it on Monday

**Review by antonrohr — APPROVED** [review]
In general looks good to me!

1. Can you add a test case that tests case insensitivity. Its probably not strictly necessary, but it would give me some piece of mind knowing that this will still work even with `c:\` vs `C:\`
2. May I ask what the problem was before and why it works now?

**Comment by beckerhe** [comment]
> In general looks good to me!
> 
> 1. Can you add a test case that tests case insensitivity. Its probably not strictly necessary, but it would give me some piece of mind knowing that this will still work even with `c:\` vs `C:\`
> 2. May I ask what the problem was before and why it works now?

I can add a test for case-sensitivity. Regarding the problem: It is described in the commit message, but here in short:
Previously the matching was made based on string prefix matching. That was fine as long as the path from debuginfo was just taken as-is and matched. But paths in debuginfo sometimes contain "/../" segments which should be stripped before doing the matching. This operation is called normalization and it also changes the path segment separator from `/` to `\` or vice-versa. So the mapping might not match anymore.

The solution: No string-base comparison, but segment-wise comparison.

**Comment by beckerhe** [comment]
> > In general looks good to me!
> > 
> > 1. Can you add a test case that tests case insensitivity. Its probably not strictly necessary, but it would give me some piece of mind knowing that this will still work even with `c:\` vs `C:\`
> > 2. May I ask what the problem was before and why it works now?
> 
> I can add a test for case-sensitivity. Regarding the problem: It is described in the commit message, but here in short:
> Previously the matching was made based on string prefix matching. That was fine as long as the path from debuginfo was just taken as-is and matched. But paths in debuginfo sometimes contain "/../" segments which should be stripped before doing the matching. This operation is called normalization and it also changes the path segment separator from `/` to `\` or vice-versa. So the mapping might not match anymore.
> 
> The solution: No string-base comparison, but segment-wise comparison.

Okay, on a second thought regarding case-sensitivity: I don't think that's a good idea. Doing string comparisons in the first approach was done on purpose: Because if the paths don't match byte-wise, it's clear that the mapping shouldn't match. Consider the following examples:

Two devs compile unreal, the first one uses C:\ue4 as its root directory, the second C:\UE4. These paths also end up in the debug information. Seeing a path C:\ue4\Engine\Source\whatever.cpp shouldn't match a mapping for C:\UE4 because this mapping was clearly created from different debug information. WDYT?

**Comment by antonrohr** [comment]
> The solution: No string-base comparison, but segment-wise comparison. 

Thank you for the explanation! I indeed did not look at the commit messages. It makes a lot of sense now. 

Regarding the case sensitivity. I am still a little torn. I think your explanation to not match with different capitalization makes sense and I lean towards you should keep it case sensitive. But also, I think Windows filesystem is on default case insensitive, so `C:\UE4` actually is the same location as `c:\ue4`. 

What I care about is, that it is clearly defined and ideally I can look at the tests to see how the matching behaves. So maybe one test for case sensitivity with 1 good (can be matched because same capitalization) and 1 bad example (cant be matched because different capitalization) is a good idea.

**Comment by beckerhe** [comment]
> > The solution: No string-base comparison, but segment-wise comparison.
> 
> Thank you for the explanation! I indeed did not look at the commit messages. It makes a lot of sense now.
> 
> Regarding the case sensitivity. I am still a little torn. I think your explanation to not match with different capitalization makes sense and I lean towards you should keep it case sensitive. But also, I think Windows filesystem is on default case insensitive, so `C:\UE4` actually is the same location as `c:\ue4`.
> 
> What I care about is, that it is clearly defined and ideally I can look at the tests to see how the matching behaves. So maybe one test for case sensitivity with 1 good (can be matched because same capitalization) and 1 bad example (cant be matched because different capitalization) is a good idea.

Thanks. Done!

**Pull request merged**
