### PR TITLE
Add UprobesUnwindingVisitor test for FrameData::map_info == nullptr

### PR DESCRIPTION
**Pull request by dpallotti**
After libunwindstack update in https://github.com/google/orbit/pull/3627.

Bug: http://b/230436550

Test: Run it.

### CODE REVIEW

**Comment by dpallotti** [comment]
Only the last commit. The rest is https://github.com/google/orbit/pull/3627 and I will have to rebase.

**Review by florian-kuebler — APPROVED** [review]
Thanks! Looks good to me!

I am wondering, if we also need to change anything here for the frame pointer/leaf function case? Probably not, right?

**Comment by dpallotti** [comment]
> I am wondering, if we also need to change anything here for the frame pointer/leaf function case? Probably not, right?

As far as I understand, this field is only used in the "stack sample" case. Maybe double check if I'm missing something.

**Comment by florian-kuebler** [comment]
> > I am wondering, if we also need to change anything here for the frame pointer/leaf function case? Probably not, right?
> 
> As far as I understand, this field is only used in the "stack sample" case. Maybe double check if I'm missing something.

Yes, lgtm.

**Pull request merged**
