### PR TITLE
Remove Save Preset action

### PR DESCRIPTION
**Pull request by IrinaShkviro**
Bug: http://b/159983695.

Remove "Save Preset".

### CODE REVIEW

**Comment by pierricgimmig** [comment]
I don't think we support loading multiple presets, *yet*, but it's definitely the plan.  I like what @dpallotti suggests, that we could remove the "Save Preset" altogether in favor of "Save Preset As", or maybe "Save as Preset". I'd vote for removing the "Save Preset" option.

**Comment by ronaldfw** [comment]
Warning: Long text, sorry.

Loading of multiple presets actually works (I just tested it). 

To address the comments: I think this whole area is tricky to get right, in particular, if we want to support loading multiple presets (which I think we do). At all steps, it needs to be completely clear to users what their actions will do regarding the preset state. This is not a tool that users use every day, so making this as obvious and explicit as possible is important, IMO.

I agree with the concerns around "Save preset" (overwriting the last opened file, etc.), but I also think there is value in having that operation as a shortcut to avoid going through the file dialog. 

As a quick fix, I think either of the following two options would work:
1) Remove "Save preset" entirely. This makes it very clear to users what they are doing. 
2) If we want to keep it: Add a dialog that says: "This will overwrite <preset>.opr. Continue?", ideally with a (sticky) checkbox "Don't ask me again.". This also makes it clear to the user what is happening and is quicker than the file dialog. In the case of multiple open presets, I think we should open the file dialog (which makes me question further whether the option "Save preset" is really that useful). 

Since 1) is simpler, I have a preference for that option.

I also wanted to add some thoughts on loading multiple presets, adding to what @dpallotti said above: Getting the union of presets is useful, but can also be confusing as it may not be what a user expects. Sometimes you want the union, sometimes you just want to load a preset and have only those functions hooked. 

My current thinking is:
- Loading multiple presets is possible, but only by multi-selecting multiple presets, either in the "presets view" or in the file dialog. This will load the union of hooked functions. Handling errors here can be tricky in how this is communicated to the user (for example, should a single "bad" preset cause the entire loading operation to fail?). 
- Loading a single preset will always unhook currently hooked functions and hook the functions in the preset.

**Comment by ronaldfw** [comment]
@IrinaShkviro When we discussed this over chat, we agreed on keeping "save session", but based on the discussion here I think we should just get rid of it. Apologies!

**Comment by IrinaShkviro** [comment]
Thanks @dpallotti @pierricgimmig  and @ronaldfw  so much for the comments! I removed "Save Preset" action. So we have only "Save Preset As" now (should we rename it?).

**Pull request merged**
